### ISSUE TITLE
[Assigned] Add ripple effect on the topic search row.

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#100]
## Overview (Required)
Title says everything 😉 

<img width="444" alt="20180113_172228_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34904290-5f835fb4-f886-11e7-9942-19c7e3527242.png">

**Comment by sho5nn** [comment]
👀

**Comment by konifar** [comment]
@sho5nn 👍  Assigned!

**Comment by sho5nn** [comment]
Also occurred in speaker search row.

![screenshot_1515842080](https://user-images.githubusercontent.com/6926816/34905590-6bdc5a04-f89f-11e7-89f8-77c264626abb.png)

**Comment by konifar** [comment]
@sho5nn Right! Actually I reported it as another issue https://github.com/DroidKaigi/conference-app-2018/issues/102 .
If you can tackle this too, please assign yourself to #102 too 🙏
