### ISSUE TITLE
[Assigned] Highlight the searched text

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#101]
## Overview (Required)
It's better to make  the searched text highlight / bold-styledwhen we search the sessions by text.

<img width="400" alt="20180113_172454_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34904316-c680541a-f886-11e7-8a1e-95183de53c88.png">

**Comment by takahirom** [comment]
I think this is duplicated issue  
But your image is very good.👍
So I close following issue
https://github.com/DroidKaigi/conference-app-2018/issues/18

**Comment by konifar** [comment]
Oh, sorry! I missed it 🙇  Thanks for arranging!

**Comment by mhidaka** [comment]
@syarihu Thank you for your quick work!
