### ISSUE TITLE
[Assigned] Kotlinize build.gradle

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#110]
## Overview (Required)
- We can use build.gradle.kts instead of build.gradle
- I think Kotlin is great. So we should use it 👍 

## Links
- https://kotlinlang.org/docs/reference/using-gradle.html

**Comment by katsutomu** [comment]
Can I try this issue? 🙋

**Comment by konifar** [comment]
Thanks! You are braver 😄

**Comment by katsutomu** [comment]
Thank you! I'll give it a try. 🙇

**Comment by katsutomu** [comment]
@konifar 
Good evening! ! !

I'm sorry. I will give up on this issue 🙇 
I tried to map versions.gradle, but I could not do it.

please, remove assign... 🙇

**Comment by takahirom** [comment]
@katsutomu Thank you for challenging 👍 I am waiting for your next challenge.

**Comment by konifar** [comment]
Thanks! Good challenge!

**Comment by shikajiro** [comment]
May I challenge this issue?

**Comment by jmatsu** [comment]
Yes, please!

**Comment by takahirom** [comment]
@shikajiro 
Thanks! Assigned!

**Comment by shikajiro** [comment]
(๑•̀ㅂ•́)و✧

**Comment by shikajiro** [comment]
@takahirom 
please change status open. assign to me.
someday pull request will be given when kotlin-dsl is stabilized.
（kotlin-dslがいつか安定したらまたPRしたいので、担当を僕にして、オープンにしててくださいませんかー！？）

**Comment by takahirom** [comment]
Sure!

**Comment by konifar** [comment]
🆒
