### ISSUE TITLE
Refactor gradle dependencies

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#111]
## Overview (Required)
I prefer creating the versions file and use the variables like this.
https://github.com/konifar/material-cat/blob/introduce_dagger/versions.gradle
https://github.com/konifar/material-cat/blob/introduce_dagger/app/build.gradle#L120

I think it's good way if we'll divide our app to some modules.
What do you think?

**Comment by konifar** [comment]
Or this might be better way?
https://github.com/googlesamples/android-architecture-components/blob/master/versions.gradle

**Comment by Pluu** [comment]
Personally, `material-cat` seems to be good.

**Comment by jmatsu** [comment]
Both ways seem to be fine with me. How about you, @takahirom?

**Comment by takahirom** [comment]
I think this project almost single module. 
What did you do for? 🤔

**Comment by konifar** [comment]
Yes, actually it's not required task. It's just my taste 😉

**Comment by takahirom** [comment]
I agree to refactor for reference. 👍 
There is no strong opinion about this refactoring.
Can I change the version number with a single line change in the material-cat method?
Should we modify each line?

```
                    v4          : "com.android.support:support-v4:26.0.2",
                    appCompat   : "com.android.support:appcompat-v7:26.0.2",
                    cardView    : "com.android.support:cardview-v7:26.0.2",
                    design      : "com.android.support:design:26.0.2",
                    recyclerView: "com.android.support:recyclerview-v7:26.0.2",
                    annotations : "com.android.support:support-annotations:26.0.2",
                    palette     : "com.android.support:palette-v7:26.0.2",
                    multidex    : "com.android.support:multidex:1.0.1",
```
