### ISSUE TITLE
[Assigned] OSS License screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#12]
# Overview
This is necessary to comply with the OSS license.

**Comment by neonankiti** [comment]
@takahirom 
Is that enough to implement this as follows? 
https://developers.google.com/android/guides/opensource

**Comment by konifar** [comment]
@neonankiti Cool. Actually I didn't know the plugin.
Can you put the screenshot of the output page?

**Comment by neonankiti** [comment]
These are the ones!! 
<img src="https://user-images.githubusercontent.com/6552589/34905889-f7083848-f816-11e7-80b2-0253bd247c92.png" width="300"> <img src="https://user-images.githubusercontent.com/6552589/34905888-f6f0dc0c-f816-11e7-8c59-950f904f00f6.png" width="300">

**Comment by takahirom** [comment]
I want to use it. But .. This app has some imported code. Do you think about it? 🤔 
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/EllipsizingTextView.java
https://github.com/DroidKaigi/conference-app-2018/blob/69d8b4282558822281a9a128f20902b88af5219d/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/transition/Rotate.java

**Comment by takahirom** [comment]
I noticed. Currently This app not using EllipsizingTextView. 🤔

**Comment by neonankiti** [comment]
@takahirom 
Actually, I'm not familiar with licenses, so we need to make sure if there is one who can clarify it. 
But from the references that I read, it looks like alright because we already include the license in the view(screenshot) above. (Both Apache v2.0)

http://vividcode.hatenablog.com/entry/license/android-app-with-apache-license-2.0
http://android-apps.at-virtual.com/android/apache-licence-2-0%E3%81%A3%E3%81%A6%E3%81%A9%E3%81%86%E6%9B%B8%E3%81%91%E3%81%B0%E3%81%84%E3%81%84%E3%81%AE%E3%81%95/

**Comment by takahirom** [comment]
I rethink.
Probably we are open source, so we don't have to write the license. And we write on README.
But we want to show that for Reference.
I think it is ok to use Google Play Services License Screen. What do you think?

**Comment by konifar** [comment]
Let's try to use Google Play Services License Screen!

**Comment by neonankiti** [comment]
Btw, where is it supposed to be put in? 
I couldn't find it out in design. 
The left task is only the transition.  
Can you guys please let me know where it is? 
I'll handle it right after knowing it.

**Comment by takahirom** [comment]
I think it is probably in "about screen".

**Comment by konifar** [comment]
Yes, it's enough to put the link into `AboutFragment`.
@neonankiti Can you create the simple link in the fragment?
