### ISSUE TITLE
[Assigned]Delete unused EllipsizingTextView

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#120]
## Overview (Required)
- Currently, DroidKaigi app doesn't use EllipsizingTextView.
- So we should delete it.
- Please delete file and README.md mention

**Comment by Pluu** [comment]
🙋

**Comment by takahirom** [comment]
@Pluu Thanks 👍Assigned!

**Comment by konifar** [comment]
@Pluu Hi again!! I'm so glad you'll contribute! Thanks 👍

**Comment by Pluu** [comment]
@konifar Thank you!! I was waiting for the DroidKaigi app Repository to be opened.
