### ISSUE TITLE
[Assigned] Settings screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#13]
# Overview

This screen contains the following settings.

- Enable Notification
- Use Local time

 We can do it with PreferenceFragmentCompat

**Comment by eyedol** [comment]
I'm interested in this. If it's not taken, I'm happy to take it.

**Comment by konifar** [comment]
Thanks! You contributed last year, right?
I'm so glad you'll contribute again! 😄

**Comment by eyedol** [comment]
Yes, I contributed last year and attended the conference too. Though this year I won't be able to make it to the conference.
