### ISSUE TITLE
[Assigned] Contributors screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#14]
# Overview
In this screen, you will see a list of contributors.
This screen may use GitHub API
Design
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a539ca700a269f5c166755b
https://scene.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a539ca700a269f5c166755b

**Comment by kaelaela** [comment]
🙋

**Comment by konifar** [comment]
@kaelaela Thanks for tackling this tough task! I assigned you! Feel free to ask us if you have any questions.

**Comment by takahirom** [comment]
👏

**Comment by takahirom** [comment]
@kaelaela I invited you to Zeplin Project 🎨

**Comment by kaelaela** [comment]
@takahirom Thx ;-) I confirmed it. 👍

**Comment by kaelaela** [comment]
@takahirom @konifar Is this Github user's bio ?🤔 
<img width="721" alt="screen shot 2018-01-15 at 12 32 55" src="https://user-images.githubusercontent.com/3871115/34926561-a9d4277e-f9f3-11e7-8ace-8e133bed588b.png">

**Comment by konifar** [comment]
@kaelaela Maybe so. I'm not sure the data is included in API response though 🙇 
If we can not get the bio, it's okay to implement it with the name simple line.

**Comment by kaelaela** [comment]
@konifar [Contributors API](https://developer.github.com/v3/repos/#list-contributors) response has no bio content. 😢 Sorry, I will implement only name. 🙇  Thx.

**Comment by konifar** [comment]
Sure sure. It's okay!
