### ISSUE TITLE
[Assigned] Apply HorizontalSessionItem design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#140]
## Overview (Required)
- It is not applied design
## Screenshot
| Current | Design|
|---|---|
| ![image](https://user-images.githubusercontent.com/1386930/34908346-4121ad1e-f8d1-11e7-8085-547aef7b4430.png) | ![image](https://user-images.githubusercontent.com/1386930/34908341-279c8e72-f8d1-11e7-848c-1e05cb0c248a.png) |

**Comment by kawmra** [comment]
I wanna contribute 🙋

**Comment by konifar** [comment]
@kawmra Thanks! Assigned!
