### ISSUE TITLE
[Assigned] If session finished, we should show survey layout

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#141]
## Overview (Required)
- We want to that user send survey(セッションアンケート)

## Links
- https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a48b9d495b92da5abf337bd
(If you raised hand, I invite you)

## Screenshot
Design screenshot(Caution: Zeplin text size is not designed)
<img src="https://user-images.githubusercontent.com/1386930/34908376-f2e768cc-f8d1-11e7-982b-75242d5cf179.png" width="300" />

**Comment by MihoSasaki** [comment]
🙋

**Comment by konifar** [comment]
@MihoSasaki Thanks! Assigned you.
Can you access Zeplin file? If not, please tell me your email on [DM](https://twitter.com/konifar). I'll send the invitation.

**Comment by jmatsu** [comment]
@MihoSasaki 
Sent an invitation. Could you please check?

If you have any questions, feel free to ask us. 🥇

**Comment by MihoSasaki** [comment]
Now I can open Zeplin file! Thanks:)

**Comment by MihoSasaki** [comment]
@jmatsu @konifar @takahirom 
I have questions 🙋 

- logic of showing questionnaire component
Is it ok to compare with current time and session’s endTime of session model to define whether to show questionnaire component?

- after tapped ‘Go To Questionnaire’ view
 I’d like to know what expect to happen after tapped ‘Go To Questionnaire’ textview. 
Is there any Link of each questionnaire page provided by api?

**Comment by konifar** [comment]
> Is it ok to compare with current time and session’s endTime of session model to define whether to show questionnaire component?

I think it's okay. FYI, please consider timezone when you get the current time. This PR would help you.
https://github.com/DroidKaigi/conference-app-2018/pull/246#discussion_r161901591

> after tapped ‘Go To Questionnaire’ view

Currently there is nothing to show. Please add just comment for now 🙇
