### ISSUE TITLE
[Assigned]Modify speaker search layout

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#148]
## Overview (Required)
<img width="612" alt="20180114_114707_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34912292-034fab08-f921-11e7-8087-976f6f943f19.png">

## Links
Sorry, we don't have the design data 🙇

**Comment by MihoSasaki** [comment]
🙋

**Comment by takahirom** [comment]
@MihoSasaki Thank you 👍 Assigned!

**Comment by MihoSasaki** [comment]
I modified like the below layout. Would it be fine?
<img width="368" alt="2018-01-14 13 30 21" src="https://user-images.githubusercontent.com/15154826/34912893-4d251132-f930-11e7-86b1-bea1d91ed87a.png">

**Comment by takahirom** [comment]
@konifar What do you think?

**Comment by konifar** [comment]
Thanks! I think it's better to make the top and bottom margin larger.
Can you change them to 16dp? 🙇
