### ISSUE TITLE
[Assigned]Collapse header in the sessions by topic page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#154]
## Overview (Required)
I think this area should be collapsed with animation when we scroll up.
Can anyone implement by using CollapsingToolbar and AppBar?

<img width="400" alt="20180114_122534_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34912487-54a4e9f0-f926-11e7-8ec8-079a61a9942a.png">

**Comment by t-kashima** [comment]
🙋

**Comment by takahirom** [comment]
@t-kashima Thank you 👍 Assigned
