### ISSUE TITLE
Kotlin coding style guide?

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#156]
## Overview (Required)
Currently we don't have any coding style guide.
Is it necessary for this project?
Can anyone create the draft to make discussion effective?

## Link
- https://github.com/raywenderlich/kotlin-style-guide

**Comment by takahirom** [comment]
We already applied Android Kotlin Style Guide by KtLint.
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/build.gradle#L177
https://android.github.io/kotlin-guides/style.html

But, some expression is not caught up by KtLint.
And some sentence, I don't keep to the regulations
Like this.

```
Expression functions should not wrap to two lines. If an expression function grows to require wrapping, use a normal function body, a return declaration, and normal expression wrapping rules instead.
```

So we should apply that rule.

If it is not enough, I think that it is better to define it on its own

**Comment by konifar** [comment]
I think KtLint is enough 👍  Thanks!

**Comment by konifar** [comment]
Okay, this is unnecessary for now 😉 
Let me close!
