### ISSUE TITLE
Add line wrap 100 characters to codeStyleSettings.xml

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#163]
## Overview (Required)
- Currently, line wrap is not working.

**Comment by ytRino** [comment]
I noticed Java code style has `Ensure right margin not exceeded`, that enforces columns in line, but kotlin code style does not.
![image](https://user-images.githubusercontent.com/1487505/34913225-b630de86-f93a-11e7-986a-0a3a8f07dcf5.png)

Also I found that when `Ensure right margin not exceeded` is checked, codeStyleSettings generate `<option name="WRAP_LONG_LINES" value="true" />` for java block. And copy-pasting it to kotlin block enables this feature 😱 .

```diff
        <codeStyleSettings language="kotlin">
          <option name="METHOD_ANNOTATION_WRAP" value="1" />
+         <option name="WRAP_LONG_LINES" value="true" />
        </codeStyleSettings>
```

The other thing i know about this:
- Modifying any option in code style remove this change 🚨 .
- Though if the option has been removed, last config is enabled (WRAP_LONG_LINES exists as true). I don't know lifetime of this behavior.
