### ISSUE TITLE
[Assigned] Remove the margin in the item layout

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#172]
## Overview (Required)
I think the item layout should not have `margin`.
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/layout/item_speech_session.xml#L31

The spacing between the items should be specified by `ItemDecoration`.

Caution: This layout is used in some places.

**Comment by Taishi-Y** [comment]
🙋‍♂️

**Comment by konifar** [comment]
@Taishi-Y Thanks! Assigned you 😉
