### ISSUE TITLE
[Assigned]SessionDetailFragment contents area is feel narrow

### ISSUE THREAD

**Issue by amay077** [DroidKaigi/conference-app-2018#180]
## Overview (Required)

In session detail screen,
I hope session header collapse when scroll to bottom (like a [droidkaigi2017 apps](https://github.com/DroidKaigi/conference-app-2017)).
So I think we should apply ``CoordinatorLayout`` to ``SessionDetailFragment``.

Do you have any plan or design?

## Links
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a5b4b2d998a44940dcba2d5?ref=slack

## Screenshot
<img src="https://user-images.githubusercontent.com/401369/34915632-0eafec78-f96d-11e7-9093-41249f95ea4b.png" width="300" />

**Comment by konifar** [comment]
Sorry, we have any interaction design here.
I guess this is intentional. The header area (like the title and the user name) contains most important information to judge whether the user join the session. These data and the heart button should not be hidden.

But I know your idea too. The scroll area is too small!!
I'll follow the designer. What do you think? @yuki2478

**Comment by konifar** [comment]
@amay077 I asked to the designer and he has the same idea of yours 😄 
Thanks for good issue!

**Comment by amay077** [comment]
@konifar I understand and change title. 👍

**Comment by YusukeIwaki** [comment]
Also, it would be better to apply a theme to the header (ConstraintLayout or AppBarLayout) of SessionDetailFragment.
Currently all of the TextView in the header have the black text color by default, and are set to white manually... 😅 
Applying `@style/ThemeOverlay.AppCompat.Dark.ActionBar` would solve it.

**Comment by konifar** [comment]
Absolutely!

**Comment by HaSuzuki** [comment]
I wanna try this!!

**Comment by konifar** [comment]
Thanks! Assigned.
I'll send the invitation to access Zeplin. Can you tell me your email onDM?
twitter.com/konifar

**Comment by HaSuzuki** [comment]
sent a DM!!

**Comment by HaSuzuki** [comment]
I want push permission of the branch plz;

**Comment by jmatsu** [comment]
Please fork this repository and push the branch to *your* repository. 
After that, you can create a Pull request to this repository.

**Comment by HaSuzuki** [comment]
ok thx!
