### ISSUE TITLE
[Assigned]Don't fix the bottom area in the session detail page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#181]
## Overview (Required)
According to the designer @yuki2478 , the bottom area on the session detail page should not be fixed.
This area should be in the bottom of ScrollView.

<img width="400" alt="20180114_212911_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34915921-35cfb680-f972-11e7-9215-6fb8909c9bf9.png">

**Comment by rmakiyama** [comment]
I want to try🙌

**Comment by takahirom** [comment]
@rmakiyama Thanks! 👍 Assigned 🙌

**Comment by mhidaka** [comment]
Great works! 🥇
