### ISSUE TITLE
[Assigned] Show the speaker detail when the icon is clicked

### ISSUE THREAD

**Issue by thagikura** [DroidKaigi/conference-app-2018#194]
## Overview (Required)
- I think showing a speaker bio is helpful when the icon of the speaker is clicked to know more about the speaker.

**Comment by furusin** [comment]
🙋

**Comment by furusin** [comment]
[help wanted]
Do we need a link to a speaker detail View from sessions list view and search view?
In my opinion, we just need a link from session detail view.

**Comment by mhidaka** [comment]
👀

**Comment by konifar** [comment]
I think it's better to add the link as you said.
But I remember some sessions have several speakers. We have to consider how to handle them when the user tap the icons view.

**Comment by furusin** [comment]
i appreciate your cooperation.
Some sessions have several speakers like this : https://droidkaigi.jp/2018/timetable?session=15984 .
so I'll try to improve SpeakersSummaryLayout at first.

**Comment by konifar** [comment]
@furusin 🆒

**Comment by takahirom** [comment]
@yuki2478 
What do you think about this layout? (Details will be fixed later)
![image](https://user-images.githubusercontent.com/1386930/35148507-ca069d14-fd55-11e7-80cd-69ab8229be96.png)
