### ISSUE TITLE
[Assigned] StatusBar color on Contributor screen is different from other screens

### ISSUE THREAD

**Issue by yagi2** [DroidKaigi/conference-app-2018#212]
## Overview (Required)
StatusBar color on Contributer screen is not primary dark color. This is defferent from other screens.  
I'm confirming this phenomenon with the Pixel2 emulator(API 24) and Nexus 5X(API 27).

## Screenshot
|Contributor screen|Session detail screen|
|---|---|
|<img src="https://user-images.githubusercontent.com/2609073/34970396-93e8c626-fab7-11e7-99ed-5eb77b3862da.png" width="300" />|<img src="https://user-images.githubusercontent.com/2609073/34970401-98f8d0d4-fab7-11e7-93d4-925b57300cfc.png" width="300" />|  

These screenshots were taken with Nexus 5X.

**Comment by kaelaela** [comment]
@yagi2 Thank you for reporting. 🙆

**Comment by KensukeIzumi** [comment]
I'll do this one!

**Comment by konifar** [comment]
@KensukeIzumi Thanks! Assigned!

**Comment by takahirom** [comment]
Probably we should use DrawerLayout. That has status bar color.

**Comment by KensukeIzumi** [comment]
Thanks, I'll try that.
