### ISSUE TITLE
[Assigned]Remove custom namespace of each binding adapter definitions

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2018#215]
## Overview (Required)
- I got the following warnings:

```
(for exmaple,)

droidkaigi-conf-app-2018/app/build/tmp/kapt3/stubs/debug/io/github/droidkaigi/confsched2018/presentation/common/binding/TextBindingKt.java:19: Warning: Application namespace for attribute bind:roomName will be ignored.
...
```

- AFAIK, custom namespace `bind` will be ignored, so we don't need to write it.
- This doesn't have any impact on applications though, warnings are noisy. 🔕 

## Links
- https://android.googlesource.com/platform/frameworks/data-binding/+/1331801%5E!/

**Comment by satsukies** [comment]
🙋

**Comment by takahirom** [comment]
@satsukies Thanks 👍 Assigned
