### ISSUE TITLE
[Assigned]Add margin in the searched page.

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#222]
## Overview (Required)
Sync design.

Actual | Design
:--: | :--:
<img width="557" alt="20180116_213643_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34989332-7dece1a6-fb05-11e7-9327-bb7f3b97fc88.png"> | <img width="366" alt="20180116_213820_ _ _ _rich - droidkaigi 2018 - zeplin" src="https://user-images.githubusercontent.com/1269214/34989358-958f510e-fb05-11e7-9520-b318a6ee476f.png">

## Links
- https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a48b9e42db8817326dd696c

**Comment by nappannda** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
@nappannda Thanks! Assigned 👍 And Invited to Zeplin!
