### ISSUE TITLE
[Assigned] Add App Shortcuts

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#224]
## Overview (Required)
This is just fun task.
How about showing MySessions tab from app shortcut?

## Links
- https://developer.android.com/guide/topics/ui/shortcuts.html

**Comment by tebasakyu** [comment]
🙌 
I hope challenge this. OK?

**Comment by konifar** [comment]
Sure sure!  Thanks! 😄

**Comment by tebasakyu** [comment]
Sorry, please one day more 🙇
