### ISSUE TITLE
[Assigned] Introduce GoogleAnalytics

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#225]
## Overview (Required)
- Introduce GoogleAnalytics
- Measure each screen views and click event count in the sponsors screen

**Comment by androhi** [comment]
@konifar I have a question.
We can use Google Analytics via firebase, but do you mean that it wants to introduce Google Analytics for Android?

**Comment by konifar** [comment]
Good point!
I mean Google Analytics, not firebase analytics because it has better feature for now to analysis.  But for this app, the rich analytics tool is not necessary. So both are fine for me!

**Comment by aya2453** [comment]
@konifar 
you’re trying to introduce GA via FirebaseSDK or Google Analytics Services SDK?
Google recommend the first one.

**Comment by aya2453** [comment]
@konifar 
OK! I’ll try it.
I'd like to check results in the firebase console by myself if its' possible, but if not (probably not..), I 'll ask you to do that when I create PR.

**Comment by takahirom** [comment]
@aya2453 Thank you! 👍 I invited to Debug Firebase Project. Can you open it? 😄

**Comment by takahirom** [comment]
If you can't find the project, I will send URL!

**Comment by aya2453** [comment]
@takahirom 
Sorry but, I don't receive any e-mail 😕 
Can you send the url to the email address below?
thanks.
aya.nk.0116@gmail.com

**Comment by takahirom** [comment]
Probably I sent you 🤔 
![image](https://user-images.githubusercontent.com/1386930/35160463-8435e0ee-fd80-11e7-8002-41df8ad5c170.png)

**Comment by takahirom** [comment]
I will send url! Please wait 🙇

**Comment by aya2453** [comment]
I got it!!! thanks!!

**Comment by takahirom** [comment]
Thanks !! I will Assign 👍
