### ISSUE TITLE
[Assigned] Hide keyboard when the tab change from search tab

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#226]
## Overview (Required)
How to reproduce: 

1. Go to Search tab
2.. Search by text
3. Change tab

![first](https://user-images.githubusercontent.com/1269214/34990755-96045d0a-fb0a-11e7-817f-fdf07a629436.gif)

**Comment by from-unknown** [comment]
Let me try! 🙌

**Comment by takahirom** [comment]
@from-unknown Thanks! Assigned! 👍

**Comment by from-unknown** [comment]
I figure out how to fix this problem.
I'll make a PR tomorrow night... I mean, tonight 😅
