### ISSUE TITLE
[Assigned] Specify version code and version name

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#229]
## Overview (Required)
Use major, minor, patch for version code.
Like `0.1.0`, `1.0.0`.
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/build.gradle#L17

## Links
- This is example https://github.com/konifar/material-cat/blob/introduce_dagger/app/build.gradle#L30
- If you have better idea, we're always welcome!

**Comment by kitwtnb** [comment]
✋

**Comment by konifar** [comment]
Thanks! Assigned 👍
