### ISSUE TITLE
[Assigned] Adaptive Icon

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#242]
## Overview (Required)
- DroidKaigi icon is oreo. So if we can, create Adaptive Icon

## Links
- https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by konifar** [comment]
Interesting 👍  Do we have any resources?

**Comment by konifar** [comment]
This is also helpful.  (Sorry, this is written in Japanese 🙇 )
https://qiita.com/takahirom/items/696fb5ecaa230fa8f755

**Comment by mhidaka** [comment]
we're back!

icon image is ready 🎉 
 * https://drive.google.com/drive/folders/1CP0LIYqIHnpiUQrCXzUKRnGgyo6xrbRQ?usp=sharing
 * includes foreground and background image.

demo of the adaptive icon. we waiting for your contribution
![adaptive-icon](https://user-images.githubusercontent.com/322019/35049138-663db76e-fbe2-11e7-8a1e-853a03e5c3b7.gif)

**Comment by chigichan24** [comment]
if no one assigned, i hope to challenge this issue 🙋

**Comment by takahirom** [comment]
@chigichan24 Thanks👍Assigned!
