### ISSUE TITLE
[Assigned] Feed screen title overlap when collapse

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#245]
## Overview (Required)
- Title says everything

## Links
- Probably we can see Google I/O Implementation https://github.com/google/iosched/blob/e4364eec0d8f358215aee30cce2b4836ec169b5a/lib/src/main/java/com/google/samples/apps/iosched/feed/FeedViewHolder.java

## Screenshot
<img src="https://user-images.githubusercontent.com/1386930/35002050-b94111de-fb2b-11e7-8e8c-0d5a0143d8bc.gif" width="300" />

**Comment by sckm** [comment]
I want to try this

**Comment by konifar** [comment]
🆒  Assigned you!
