### ISSUE TITLE
[Assigned] SpeechSessionItem and DateSessionsSection should not have Fragment

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#250]
## Overview (Required)
This is simple refactoring task.
`SpeechSessionItem` and `DateSessionsSection` should not have Fragment but it seems to be never used.

**Comment by takasfz** [comment]
🙋‍♂️

**Comment by konifar** [comment]
Thanks! Assigned 👍

**Comment by konifar** [comment]
Maybe so. Sorry I can't check it soon 🙇 
Please go ahead. We can review the fix by PR review and CI!
