### ISSUE TITLE
[Assigned] Comment Android Lint error to pull request

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#258]
## Overview (Required)
- Currently, droidkaigibot(Danger) comment by KtLint. But bot does not comment by Android Lint. 
- I think Android Lint **warnigs** is buggy with Kotlin. So I don't want to comment it.  But Android Lint **errors** is sometimes useful and we do not use `abortOnError = false`. So we should keep it.

- Please comment Android Lint Error to pull request 🙇

**Comment by yatatsu** [comment]
Hi, I hope to challenge this! 🙋

**Comment by takahirom** [comment]
@yatatsu Thanks! Assigned 👍
