### ISSUE TITLE
About this app screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#27]
# Overview
With this function, Users can know about this app
You should implement [AboutThisAppFragment](https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/about/AboutThisAppFragment.kt)

# Links
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a5b17ff4d545fa82084b089
(If you raised hand, I invite you)

# Related PRs
- [ ] [transition to license](https://github.com/DroidKaigi/conference-app-2018/pull/121)

# Screenshot
Design screenshot(Caution: Zeplin text size is not designed)
![image](https://user-images.githubusercontent.com/1386930/34918079-030f430e-f991-11e7-864f-96d8ccca3ba6.png)

**Comment by neonankiti** [comment]
It's including License. I'll pick this up.

**Comment by neonankiti** [comment]
@takahirom Plz let me access the Zeplin.

**Comment by takahirom** [comment]
@neonankiti Invited! Thanks 👍
