### ISSUE TITLE
[Assigned] Show heads up notification when my session starts

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#275]
## Overview (Required)
- You can check notification adding mysession and changing time to droidkaigi day in device setting.

**Comment by geckour** [comment]
Let me try🙋

**Comment by takahirom** [comment]
@geckour  Thank you for your tring! 👍 Assigned

**Comment by geckour** [comment]
Plz let me ask some questions...
- Is "my session" meaning favorited sessions?
- Should vibrate when notification has published?

**Comment by takahirom** [comment]
@geckour 
> Is "my session" meaning favorited sessions?
YES!
> Should vibrate when notification has published?
Please don't use vibrate.
Please use setFullScreenIntent.  I know it is sometimes strange behavior.🙇

**Comment by geckour** [comment]
@takahirom 
I got it! Thanks👍
