### ISSUE TITLE
[help wanted] Firestore will not return a response after a long time since you started using it.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#277]
## Overview (Required)
- We can not use favorite!! 😭 
- I can fix it clear app data. So probably, app internal problem.
- I can't fix this by force stop app.
- It occurred release and debug
- If it occurred, FavoriteFirestoreDatabase "Firestore:setupFavoritesDocument" is logged, But "Firestore:setupFavoritesDocument onComplete" is not logged.

https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFirestoreDatabase.kt#L100

```kotlin
    @CheckResult
    private fun setupFavoritesDocument(currentUser: FirebaseUser): Single<FirebaseUser> {
        return Single.create({ e: SingleEmitter<FirebaseUser> ->
            if (DEBUG) Timber.d("Firestore:setupFavoritesDocument")
            val database = FirebaseFirestore.getInstance()
            val favorites = database.collection("users/" + currentUser.uid + "/favorites")
            favorites.get().addOnCompleteListener { task ->
                if (DEBUG) Timber.d("Firestore:setupFavoritesDocument onComplete")
```

**Comment by takahirom** [comment]
Sorry, this issue is occurred by change device time.
I debugging this. So it occurred.
https://github.com/DroidKaigi/conference-app-2018/pull/244

**Comment by takahirom** [comment]
It has occurred when does not change device time 🤔  Reopen... 😭 
https://twitter.com/muumuumuumuu/status/954558896667947008

**Comment by Kesin11** [comment]
I did reproduce this issue may be.
In my case, same behaviour occurs when launch app without network connection.

1. Turn off wifi
2. Launch app
3. **Turn on wifi**
4. Touch favorite icon in AllSessionsFragment. Icon is turned on
5. Go to session detail
6. Favorite icon is still turned off

I tried to repeat step 4 to 6 after turned on wifi, it still same result. But after about 1 minutes, it revived suddenly.
However, I can not see any log in setupFavoritesDocument()

**Comment by takahirom** [comment]
Thanks! I will try it!

**Comment by takahirom** [comment]
I reproduced
Probably I think It related offline 🤔

**Comment by takahirom** [comment]
Here?
https://github.com/droidkaigi/conference-app-2018/blob/642bf75efd688f85f7f810b48944ed52b033f51e/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/App.kt#L42-L42

**Comment by nukka123** [comment]
I try Kesin11’s reproduce procedure. 
(env: emulator api27)
After step 6, It seems to be kept waiting for 8 minutes.

(sorry, I am not familiar with Firebase.)

```
01-25 20:21:10.926 5161-5161/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$getCurrentUser: Firestore:Get cached user
(The above log appears in step 4)
...
01-25 20:29:12.047 5161-5161/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$favorite: Firestore:favorite get
01-25 20:29:12.061 5161-5161/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$getFavorites$1$eventListener: Firestore:getFavorites onChange
01-25 20:29:12.061 5161-5161/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$getFavorites$1$eventListener: Firestore:getFavorites onChange [16969]
01-25 20:29:12.061 5161-5161/io.github.droidkaigi.confsched2018.debug D/SessionDataRepository$sessions: favorites
01-25 20:29:12.068 5161-5161/io.github.droidkaigi.confsched2018.debug D/SessionDataRepository$sessions: size:90 current:1516879752068
01-25 20:29:13.318 5161-5161/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$favorite$1$1$1$completeListener: Firestore:favorite write success
```

It may be related.
https://qiita.com/osamu1203/items/23df0b135ed0548ff73b
> ただし、100%lossの時（通信不安定）は、読み込み待ちが発生しキャッシュからもデータを引き出す事ができず待たされます。

**Comment by kakajika** [comment]
Hello 🙋  First comment on this project!

I think it's a problem about Firestore's behavior when device is regarded as offline.

The official document of Firestore says:

> If you get a document while the device is offline, Cloud Firestore returns data from the cache. If the cache does not contain data for that document, or the document does not exist, the get call returns an error.

https://firebase.google.com/docs/firestore/manage-data/enable-offline#get_offline_data

So, if the document is empty, `favorites.get()` cause error and return nothing.
We should use `favorites.addSnapshotListener(...)` instead.

```kotlin
    @CheckResult
    private fun setupFavoritesDocument(currentUser: FirebaseUser): Single<FirebaseUser> {
        val database = FirebaseFirestore.getInstance()
        val favorites = database.collection("users/" + currentUser.uid + "/favorites")

        return Single.create({ e: SingleEmitter<QuerySnapshot> ->
            if (DEBUG) Timber.d("Firestore:setupFavoritesDocument")
            val listener = favorites.addSnapshotListener { querySnapshot, exception ->
                if (DEBUG) Timber.d("Firestore:setupFavoritesDocument onComplete")
                if (exception != null) {
                    Timber.e(exception, "Firestore:setupFavoritesDocument onComplete fail ")
                    e.onError(exception)
                } else {
                    e.onSuccess(querySnapshot)
                }
            }
            e.setCancellable {
                listener.remove()
            }

        // To avoid [ get -> write -> get -> ... ] loop, make task split.
        }).flatMap { querySnapshot ->
            Single.create<FirebaseUser> { e ->
                if (querySnapshot.isEmpty) {
                    favorites.add(mapOf("initialized" to true)).addOnCompleteListener {
                        if (DEBUG) Timber.d("Firestore:create document for listing")
                        e.onSuccess(currentUser)
                    }
                } else {
                    if (DEBUG) Timber.d("Firestore:document already exists")
                    e.onSuccess(currentUser)
                }
            }
        }
    }
```

I tried code above, and it seems to work well.
If It's OK, I create PR! 😃

**Comment by takahirom** [comment]
Thanks recommend addSnapshotListener 🥇 
I worried about calling multiple time the changing listener. 
If you can, Please add log here. and Please check setCancellable is called.

```
            e.setCancellable {
                listener.remove()
            }
```

**Comment by kakajika** [comment]
OK, I've added logs and checked it!

```
01-26 10:55:43.662 12149-12378/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$setupFavoritesDocument: Firestore:setupFavoritesDocument
01-26 10:55:46.551 12149-12149/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$setupFavoritesDocument$1$listener: Firestore:setupFavoritesDocument onComplete
01-26 10:55:46.552 12149-12149/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$setupFavoritesDocument: Firestore:document already exists
01-26 10:55:46.557 12149-12149/io.github.droidkaigi.confsched2018.debug D/FavoriteFirestoreDatabase$setupFavoritesDocument: Firestore:setupFavoritesDocument dispose
```

**Comment by takahirom** [comment]
Thanks 👍 
Please PR!
You are professional for Firestore 👨‍🎓
