### ISSUE TITLE
Improve Chrome custom tab else

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2018#283]
## Overview (Required)

- As you can see, the current app opens a web page by using Chrome custom tabs. But its settings just satisfy minimum requirements.
- So we are welcome improvements. e.g.  Support devices which don't have Chrome, opt-out Chrome tabs...

## Links
- https://github.com/DroidKaigi/conference-app-2018/blob/b4f9293aed2edbd6dfddfb5658334a0c4283513c/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/NavigationController.kt#L125

**Comment by ytRino** [comment]
im looking this just open browser when customtabs does not available
