### ISSUE TITLE
[Assigned] Show progressbar for sponsor list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#285]
## Overview (Required)
- It takes time show sponsor list, So we should show progress bar for Sponsor list
- Please use `ProgressTimeLatch` class

**Comment by youta1119** [comment]
can i try it?

**Comment by konifar** [comment]
Sure! Thanks!

**Comment by jmatsu** [comment]
I might leave a TextView whose name is `empty`... please delete it if still exists 🙇
