### ISSUE TITLE
[Assigned] wrong margin in session feed on API Level19 emulator

### ISSUE THREAD

**Issue by punchdrunker** [DroidKaigi/conference-app-2018#287]
## Overview (Required)
-  margin or padding for session topic label is apparently broken on api level 19

## Links
-

<img width="300px" src="https://user-images.githubusercontent.com/135589/35096192-9eff5cb8-fc8e-11e7-90a0-c057d90745b6.png" />

**Comment by gen0083** [comment]
It looks like that all of TextView in API 19 have wrong padding (especially bottom).
TextView's size seems not correct in API19.
I don't know how to fix it 🤔 

![2018-01-19 15 32 34](https://user-images.githubusercontent.com/7608725/35137755-496a0104-fd2e-11e7-8528-52083c8c4d46.jpg)

left: API19 and right: API21, both on emulator

**Comment by IsseiAoki** [comment]
Can I try this issue?

**Comment by jmatsu** [comment]
Thank you so much! Assigned 👍

**Comment by IsseiAoki** [comment]
It seems that the bug is related to `android:lineSpacingMultiplier` attribute. 
If I comment out the corresponding line of the `text_appearance.xml`, it works perfectly.
But I couldn't find the solution that don't comment out the `android:lineSpacingMultiplier` attribute.
Can you give me some advice?

**Comment by takahirom** [comment]
How about using `android:lineSpacingExtra ` ?
Probably @konifar, @jmatsu are detailed about this.

**Comment by IsseiAoki** [comment]
@takahirom Thank you! I think it's nice!
@konifar @jmatsu What do you think about it?

**Comment by konifar** [comment]
I know what you mean. Agreed your suggestion to use `lineSpacingExtra`!

**Comment by IsseiAoki** [comment]
@konifar Thank you so much!! I will use `lineSpacingExtra` !

**Comment by konifar** [comment]
@IsseiAoki Thanks you too! It's too late today, take good care of yourself 😉

**Comment by IsseiAoki** [comment]
@takahirom @konifar 
I tried `lineSpacingExtra` , but unfortunately it also didn't work.
It seems the result is same as with `lineSpacingMultiplier`.
I'm sorry I can't handle this issue. Please remove assign.:bow:

Issue #288 is also the same.

**Comment by takahirom** [comment]
@konifar 
How about this? 🤔 

```
    <style name="Platform" />
    <style name="Platform.TextStyle" />
    <style name="Platform.TextStyle.App" />
    
    <style name="Platform.TextStyle.App.Title" />

    <style name="TextStyle.App.Title" parent="Platform.TextStyle.App.Title">
        <item name="android:textAppearance">@style/TextAppearance.App.Title</item>
    </style>
```

values-v21
```
    <style name="Platform.TextStyle.App.Title">
        <item name="android:lineSpacingMultiplier">1.25</item>
        <!-- 1.25 (Title is 21sp and "should exist as single lines", so adjusted manually) -->
    </style>
```

**Comment by takahirom** [comment]
@IsseiAoki 
Sorry If you have energy on this issue, Please try this style. 🙇 
If you want to give up, That's all ok 🆗

**Comment by IsseiAoki** [comment]
@takahirom 
Sure!!
Thank you for your advise! I want to try it!
