### ISSUE TITLE
[Assigned] No margin bottom when session detail is scrolled 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#290]
## Overview (Required)
- I think it need 16dp

![screenshot_20180118-223015](https://user-images.githubusercontent.com/1386930/35100469-43881120-fc9f-11e7-8757-1ecbfe865703.png)

**Comment by hkusu** [comment]
Can I try it?

**Comment by takahirom** [comment]
@hkusu OK!Assigned👍😀
