### ISSUE TITLE
Drawers on screens

### ISSUE THREAD

**Issue by daisuke-nomura** [DroidKaigi/conference-app-2018#294]
## Overview (Required)
- We can expand Drawer(Layout) on all screens. I feel that's too much.
- What do you think about Drawers except main screen?

## Links
-

**Comment by konifar** [comment]
Thanks for creating issue!
Maybe this is intentional. Let me ask to @takahirom 😄

**Comment by takahirom** [comment]
Thanks 👍 
The first time, I create activity. I faced this problem
https://github.com/DroidKaigi/conference-app-2018/issues/212
So I implement DrawerLayout and NavigationView for all activity.

But probably we can implement no navigation view by only using DrawerLayout.
We should think it 🤔

**Comment by ogapants** [comment]
Excuse me for cutting in.
When my app was featured on GooglePlay, I was ordered by Google staff to attach Drawer to **all screens**.
In my opinion, it is necessary to follow the order in order to apply material design.
(But detailed document could not be found... 🤔 )
https://material.io/guidelines/patterns/navigation-drawer.html

**Comment by eneim** [comment]
One question @takahirom : is it a must to have DrawerLayout? Or it is there is to fix #212 ? If there is a way to draw status bar color correctly between Screen, will DrawerLayout is still required?

**Comment by takahirom** [comment]
@eneim I don't have the solution of #212 without DrawerLayout.

**Comment by eneim** [comment]
@takahirom just talking about #212, [the following line](https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/values-v21/themes.xml#L5) is the cause of transparent statusBar:

```xml
<item name="android:statusBarColor">@android:color/transparent</item>
```

If you need different color, just change this value.

The reason this attribute is transparent by default is: when new Activity is created using **CoordinatorLayout** OR **DrawerLayout** as root, these layouts could automatically draw statusBarColor using **fitsSystemBar** attribute and window insets (read their source code for more information). In those case, setting the statusBar to transparent will prevent over draw.

何ですが, ConstraintLayout doesn't give that ability. So using it as root layout with the same theme will result in the transparent statusBar (as nothing is drawn). To fix this, you can either change the color in theme directly (but reusing this theme for other Activity that use CoordinatorLayout as root will cause overdraw), or (I recommend this way): create a new theme from **AppTheme.NoActionBar** and change the value of statusBarColor attribute there, use that theme only for Activity with root layout of **ConstraintLayout**.

One thing should be taken into account is: custom color for statusBar is supported from API 21 onwards, so we only need to care about those cases.

So if you don't want DrawerLayout everywhere, but only need to fix #212, please consider the solution in this comment :D.

**Comment by ogapants** [comment]
FYI, If you want to solve it programmatically, like this...

```xml
<item name="android:statusBarColor">@color/primary_dark</item>
```

`DrawerMenu.setup`
```kt
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    activity.window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
    activity.window.statusBarColor = ContextCompat.getColor(activity, android.R.color.transparent)
}
```

**Comment by takahirom** [comment]
@eneim @ogapants Thank you for solutions 👍

**Comment by daisuke-nomura** [comment]
Thanks! I'm glad to read your opinions.
Is there anyone who has an opinion or a better way about Drawer?

My thought is, a screen has a Drawer if there is a hamburger icon.
I don't know the app made by Google that has Drawer without hamburger icon.
But actually I don't understand what is better!

---

ご意見・修正方法等ありがとうございます。
ドロワーについてこうした方がいい！的なご意見をお持ち方がいらしたら是非教えてください。
僕はGoogleのアプリで、画面にドロワーがあるけどハンバーガーアイコンが配置されてないアプリを見たことがないので、合わせちゃえばいいと思ってます。
でも、何がベターなのかわかってません。

**Comment by takahirom** [comment]
I think Google Play app detail page or Gmail mail detail page and Google Music music detail page don't have hamburger icon. But It have a Drawer  🤔

**Comment by daisuke-nomura** [comment]
:satisfied:

**Comment by takahirom** [comment]
> Thanks! I'm glad to read your opinions.
Is there anyone who has an opinion or a better way about Drawer?
ご意見・修正方法等ありがとうございます。
ドロワーについてこうした方がいい！的なご意見をお持ち方がいらしたら是非教えてください。

🙏

**Comment by jmatsu** [comment]
The followings are just my opinions.

- This application has no reasons not to allow users go to any screens from any other screens.
- It would might make us easy to avoid bugs due to inconsistency of displayed components.
- DrawerLayout might annoy some of users though, it's a kind of hidden components by default.
- The current activity stack might not be suitable.

In short, it's even okay to keep the current way -- i.e. to use DrawerLayout on all screens -- though, I think it's better to re-consider activity stack strategy to improve screen transitions.

**Comment by daisuke-nomura** [comment]
@jmatsu Good perspective you have! :smile_cat:
@takahirom Keep current Drawers on screens, and make an issue for re-consider activity stack strategy to improve screen transitions?
At last, I guess Google Play detail screen is under the same activity with main screen.

@jmatsu 確かにそのとおりですね。 :smile_cat:
@takahirom 現在の全画面のドロワーはそのままにして、画面遷移改善とActivityスタックについて検討するチケットを作るのはいかがでしょう。
それと、Google Playの詳細画面ってメイン画面と同じActivityにいるっぽいです。

**Comment by jmatsu** [comment]
👀 

@daisuke-nomura 
Sorry for the delay to check 🙇 

@takahirom ping

**Comment by daisuke-nomura** [comment]
うーん 残り日数少ないですし、閉じちゃいますね
