### ISSUE TITLE
[Assigned] Link Preference and behavior of settings that use local time

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#303]
## Overview (Required)
- Currently, There is only settings screen item. So we adapt it to app behavior ⏲

**Comment by takahirom** [comment]
I want to use this 🙋 
https://github.com/chibatching/Kotpref

**Comment by takahirom** [comment]
If you want to do this you can use Prefs value like this.

```
Prefs.enableLocalTime
```

**Comment by eyedol** [comment]
I'll take it. Assign it to me.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
