### ISSUE TITLE
[Assined] Link Preference and behavior of settings that use notification

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#304]
## Overview (Required)
* Currently, There is only settings screen item. So we adapt it to app behavior :timer_clock:

## Links
-

**Comment by takahirom** [comment]
I want to use this 🙋
https://github.com/chibatching/Kotpref

**Comment by takahirom** [comment]
If you want to do this you can use Prefs value like this. 👍 

```
Prefs.enableNotification
```

**Comment by koji-1009** [comment]
Hi! Can I try this issue?

**Comment by takahirom** [comment]
@koji-1009 Thanks! Assigned 👍 😄
