### ISSUE TITLE
fragment_settings.xml is missing

### ISSUE THREAD

**Issue by ycrack** [DroidKaigi/conference-app-2018#308]
## Overview (Required)
- Build failed because of compilation failed.
- Referenced by:

1. app/build/generated/source/kapt/debug/android/databinding/DataBinderMapper.java
2. app/build/generated/source/kapt/debug/io/github/droidkaigi/confsched2018/databinding/FragmentSettingsBinding.java

Is this occurred in only my environment?

**Comment by takahirom** [comment]
Probably this problem is famous. We should rebuild 👍
