### ISSUE TITLE
[Assined] Incomplete Implementation of Notification Channel

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2018#312]
#### Deprecated Constructors.
NotificationCompat.Builder(Context context) is deprecated. use NotificationCompat.Builder(Context, String) instead. 

####  When there is no notification, the setting of the notification channel does not appear.
I recommend that you execute createNotificationChannel() at the following timing.
* Application > onCreate()
* when received ACTION_LOCALE_CHANGED.

####  The name of NotificationChannel should not use appName.
Users can visit Settings to change the NotificationChannel behaviors.
In order to allow user judgment, functional names should be given.

## Links

https://developer.android.com/guide/topics/ui/notifiers/notifications.html#CreateChannel
https://developer.android.com/reference/android/app/NotificationChannel.html#NotificationChannel(java.lang.String, java.lang.CharSequence, int)
https://qiita.com/Shiozawa/items/095e77d38fc00681e898

**Comment by takahirom** [comment]
Is it mean this implementation is not incomplete Implementation? 🤔 
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/util/NotificationUtil.kt#L17

**Comment by nukka123** [comment]
> https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/util/NotificationUtil.kt#L17

Yes!  😁

**Comment by takahirom** [comment]
Thank you for reporting 👍

**Comment by nacatl** [comment]
Can I get a permission to try this?

**Comment by takahirom** [comment]
@nacatl Thanks 👍 Assigned!
