### ISSUE TITLE
[Assigned] Progress bar in SponsorsFragment doesn't hide by conditions

### ISSUE THREAD

**Issue by adakoda** [DroidKaigi/conference-app-2018#314]
## Overview (Required)
How to reproduce:

1. Go to Sponsor view.
2. Progress bar will hide after loading, this is OK. 
2. Tap any sponsor image.
3. Tap Back key.
4. Progress bar doesn't hide, this is BUG.

![bug](https://user-images.githubusercontent.com/330223/35161284-0b65bfd8-fd83-11e7-94da-4feba4b66e5e.gif)

**Comment by eno314** [comment]
I want to do it :raised_hand:

**Comment by konifar** [comment]
@eno314 Thanks! Assigned 👍
