### ISSUE TITLE
Session time is incorrect due to Time Zone change.

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2018#322]
## Overview (Required)
The reproduction procedure is as follows.

1) Visit Settings app.
1-1) Data & time > Set Time zone to London. (GMT+00:00)
1-2) Perform CLEAR DATA of droidkaigi2018 app.
2) Launch droidkaigi2018 app. (Sessions will be displayed soon.)
3) Finish app. (Back button)
4) Visit Settings app.
4-1) Data & time > Set Time zone to Tokyo. (GMT+09:00)
5) Launch droidkaigi2018 app. (The time of the displayed session is incorrect.)

![sessiontimeincorrect](https://user-images.githubusercontent.com/29206446/35177002-e2c758f6-fdbf-11e7-9892-0a0163ec628c.png)

As an impression that I read the code, the following code has doubts.

LocalDateTimeAdapter.kt
```kotlin
private val FORMATTER: DateTimeFormatter =
        DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss")
fun parseDateString(dateString: String?): LocalDateTime =
        LocalDateTime.parse(dateString, FORMATTER)
```
I guess that the time obtained from the server is based on Japan time. 
However, the application is parsing according to current Time Zone set for the terminal?

## Links
-

**Comment by konifar** [comment]
@nukka123 Thanks for creating the issue! 👍

**Comment by konifar** [comment]
📝 Our session time is managed as JST timezone.
This code would help to fix. https://github.com/DroidKaigi/conference-app-2018/blob/453f5d1d1f5f1d4e60c3cb619cd10beeb037142a/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sessions/item/SpeechSessionItem.kt#L41

**Comment by jmatsu** [comment]
Thank you for reporting that! Your investigation looks right. :eyes:

This app is for the specific conference in Japan, so I guess this app should show time based on JST and show timezone expressly. For attendees from abroad,  timezone is one of important information.
Hi falks, what do you think?

**Comment by nukka123** [comment]
The first presented code (parseDateString) was not the cause.
I have learned LocalDateTime.
I investigated further.

There seems to be a problem with the implementation concerning LocalDateTime conversion.


1.  About toUnixMills()

```
fun LocalDateTime.toUnixMills(): Long = atZone(ZoneId.systemDefault())
        .toInstant().toEpochMilli()
```

LocalDateTime does not have TimeZone.
Time zone for this LocalDateTime object is implicitly defined by the application.
Because of the above comment, Session time is managed by JST.

It is necessary to assume that the time expressed by LocalDateTime is JST.
However, the current implementation is based on terminal dependent Time zone.

Therefore, the time held by the session is illegal.


2. About Converters.kt

```
object Converters {
    fun fromTimestamp(value: Long?): LocalDateTime? {
        if (value == null) {
            return null
        }
        return LocalDateTime.ofInstant(Instant.ofEpochSecond(value), ZoneId.systemDefault())
    }
```

It is necessary to assume that the time expressed by LocalDateTime is JST.
However, the current implementation is based on terminal dependent Time zone.

Therefore, the LocalDateTime obtained from the DB becomes illegal.


3. About "Date.toTime().toInt()"

Unix time of millisecond precision exceeds 32 bit width.
It is necessary to use Long.

ex: "2018-01-20 13:11:05" -> 1516453865 * 1000(ms)

"ToInt ()" is used in several places.
These may not work properly. (Such as sorting)

**Comment by takahirom** [comment]
Yes !toInt become overflow. We try to use java.util.Date👍
And we shoud remove toInt.
https://github.com/DroidKaigi/conference-app-2018/pull/342

**Comment by takahirom** [comment]
@nukka123 
Thank you for cheching！
>1. 2.

How do you think to solve it?

**Comment by nukka123** [comment]
@takahirom

I will introduce the code that I was verifying locally.

>> It is necessary to assume that the time expressed by LocalDateTime is JST.

```
fun LocalDateTime.toUnixMills(): Long = atZone(ZoneId.of("JST", ZoneId.SHORT_IDS))
        .toInstant().toEpochMilli()
```

```
    fun fromTimestamp(value: Long?): LocalDateTime? {
        if (value == null) {
            return null
        }
        return LocalDateTime.ofInstant(
                Instant.ofEpochSecond(value), ZoneId.of("JST", ZoneId.SHORT_IDS))
    }
```

Also, we should write javadoc about the time zone assumed by LocalDateTime.

**Comment by takahirom** [comment]
@nukka123 Looks super nice! 🥇  If you have time, Can you send PR?

**Comment by nukka123** [comment]
@takahirom

Ok. I send PR! #371

**Comment by takahirom** [comment]
Thanks! 👍

**Comment by takahirom** [comment]
3.  is already fixed 👍
