### ISSUE TITLE
[Assigned] set correct icons for About Screen.

### ISSUE THREAD

**Issue by neonankiti** [DroidKaigi/conference-app-2018#323]
## Overview (Required)
- icons below are not proper ones. adapt correct ones. 

<img src="https://user-images.githubusercontent.com/6552589/35177521-ef2bc46e-fd34-11e7-9b9e-105addd0a8d5.png" width="300">

## Links
- #316 
- [Design](https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a5b17ff4d545fa82084b089)
- [Asset](https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a53b2cc33773142c504b949)

**Comment by ycrack** [comment]
icons still not have created? I want to try add icons to their blanks.
I found the icons are drawn not PNG but XML. It is little difficult... :( but I want to try!

**Comment by konifar** [comment]
@ycrack Thanks! Icons have been added in Zeplin!
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a53b2cc33773142c504b949

I assigned you 👍

**Comment by ycrack** [comment]
@konifar Zeplin says:

> You’re not invited to this project. 

plz invite...

**Comment by konifar** [comment]
Sure. Can you tell me your email here or DM (twitter/konifar) ?

**Comment by ycrack** [comment]
Okay, I'll send you DM.
