### ISSUE TITLE
[Assigned] Resolve warning in AboutThisApps.kt

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#325]
## Overview (Required)

<img width="888" alt="conference-app-2018" src="https://user-images.githubusercontent.com/1269214/35178511-4edf7ade-fdcd-11e7-80f4-c150c578df7b.png">

**Comment by eno314** [comment]
I want to do it :raised_hand:

**Comment by konifar** [comment]
Thanks! 👍
