### ISSUE TITLE
[Assigned] Resolve waning in SessionFeedbakEntity

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#327]
## Overview (Required)

<img width="1333" alt="conference-app-2018" src="https://user-images.githubusercontent.com/1269214/35178537-ce87fdec-fdcd-11e7-8723-d8a852821c75.png">

**Comment by kazukinr** [comment]
🙋

**Comment by takahirom** [comment]
Thanks!Assigned👍
