### ISSUE TITLE
[Assigned] Use java.util.Date instead of io.github.droidkaigi.confsched2018.model.Date

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#330]
## Overview (Required)
- The first time we want to do kotlin-multi-platform. But Actually, In this project gave up. So we can use Java Date class
- model.Date sometimes occurs confusion

**Comment by t-kashima** [comment]
🙋

**Comment by konifar** [comment]
Thanks! Assigned 🌞
