### ISSUE TITLE
[Assigned] Create activitymodule package in di package and move it ActivityBuilder and ActivityModule

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#331]
## Overview (Required)
- I think there is so many classes
 https://github.com/DroidKaigi/conference-app-2018/tree/master/app/src/main/java/io/github/droidkaigi/confsched2018/di

**Comment by tatsuhama** [comment]
I want to do it

**Comment by konifar** [comment]
Thanks! Assigned 👍
