### ISSUE TITLE
[Assigned] FavoriteSessionsFragment shows session description

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#333]
## Overview (Required)
- It should like this. but master code is showing session description

![image](https://user-images.githubusercontent.com/1386930/35179233-66e8c1d8-fdd9-11e7-86c5-a87a1b0636ea.png)

**Comment by t-kashima** [comment]
🙋

**Comment by konifar** [comment]
Thanks! Assigned
