### ISSUE TITLE
[Assigned] Scroll to current session when reselected BottomNavigationView.

### ISSUE THREAD

**Issue by sho5nn** [DroidKaigi/conference-app-2018#343]
## Overview (Required)

- refs https://github.com/DroidKaigi/conference-app-2018/issues/65#issuecomment-358045345

![device-2018-01-20-175553](https://user-images.githubusercontent.com/6926816/35181893-048da2e4-fe0e-11e7-9ad6-5530f0fdf20b.png)

**Comment by bina1204** [comment]
I want to try it!

**Comment by takahirom** [comment]
@bina1204 
Thanks 👍 This is very user-friendly feature 😄
