### ISSUE TITLE
[Assigned] Add ripple effect in About app page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#346]
## Overview (Required)

<img width="454" alt="20180120_182433_screenshot_2018-01-20-18-18-41 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35181962-35807cae-fe0f-11e7-8b9e-ee8dc5d19522.png">

**Comment by verno3632** [comment]
Can I try this issue?

**Comment by konifar** [comment]
Sure! Thanks!

**Comment by verno3632** [comment]
It looks that they have ripple effect already.
Can you check it?

**Comment by takahirom** [comment]
Probably it depends on OS 🤔 ?

**Comment by takahirom** [comment]
I think ripple effect for KitKat is not needed.
I think upper social media need ripple effect!
