### ISSUE TITLE
[Assigned] Add toolbar elevation in sponsors page and contributors page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#347]
## Overview (Required)

<img width="452" alt="20180120_182845_screenshot_2018-01-20-18-27-12 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182010-cffd66c0-fe0f-11e7-9efa-f260149dd49c.png">

Contributors page as well.

**Comment by tebasakyu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
