### ISSUE TITLE
[Assinged] Adjust margin in sponsors page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#348]
## Overview (Required)
- Some margins are not aligned with the design.
- Can anyone adjust layout? 🙇 

Example
<img width="500" alt="20180120_182957_screenshot_2018-01-20-18-27-12 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182021-278b1b3a-fe10-11e7-839b-5fe5debbabb9.png">

## Links
- [Zeplin](https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a538cc21b7da4b68e177e97)

**Comment by iiinaiii** [comment]
I will try this `:raising_hand`

**Comment by takahirom** [comment]
Thanks Assigned 👍

**Comment by iiinaiii** [comment]
Could you invite me to zeplin project?
kyoumi155@gmail.com

**Comment by takahirom** [comment]
@iiinaiii Invited 😄

**Comment by iiinaiii** [comment]
Thanks!!
