### ISSUE TITLE
[Assigned] Keyboard is shown on the drawer

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#349]
## Overview (Required)
When you show keyboard on the search page and tap the drawer icon, the keyboard is not hidden.

<img width="449" alt="20180120_183659_screenshot_2018-01-20-18-36-18 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182056-f4ac37d4-fe10-11e7-8918-84aad8199ee3.png">

**Comment by from-unknown** [comment]
Another keyboard bug...!
I thought I destroyed.
:raising_hand_man:

**Comment by sho5nn** [comment]
@from-unknown Thanks! It’s up to you.

**Comment by from-unknown** [comment]
:muscle:

**Comment by from-unknown** [comment]
I'm almost done...
Probably I will make a PR tomorrow 🙇 
One thing I don't understand how it works, so I'm trying to make it clear.
