### ISSUE TITLE
Fast scroll drawable is too small in sessions page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#351]
## Overview (Required)
Is it possible to set `minHeight`? 🤔 

<img width="451" alt="20180120_184319_screenshot_2018-01-20-18-42-17 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182111-cdf3efaa-fe11-11e7-9b1f-633aa37bd032.png">

**Comment by adakoda** [comment]
I think so too, but I DON'T HAVE a solution😇

Here is the AOSP repository.
- https://github.com/aosp-mirror/platform_frameworks_support/blob/b6838fd2d2e834fdd38aab34511d385cb7108f63/v7/recyclerview/src/main/java/android/support/v7/widget/FastScroller.java
- https://github.com/aosp-mirror/platform_frameworks_support/blob/b6838fd2d2e834fdd38aab34511d385cb7108f63/v7/recyclerview/src/main/java/android/support/v7/widget/RecyclerView.java

The vertical thumb height will calculate in FastScroller#updateScrollPosition() using RecyclerView #computeVerticalScrollRange() and etc.

The only way to fix is making request to AOSP ???
Umm...
I DON'T HAVE a solution, SIKASINAGARA ORETACHI WA SITTEIRU, ANO OTOKONO NAMAE WO...😎
- http://yaraki.github.io/slides/gdm01/#35

**Comment by konifar** [comment]
@adakoda Understood. THIS IS ANDROID
Then, let me close this issue for now. Thanks for your detailed explanation!

**Comment by adakoda** [comment]
This problem had already registered in AOSP issue tracker.
The issue is here.
https://issuetracker.google.com/issues/64729576

Please mark it to increase the priority by star!
