### ISSUE TITLE
[Assigned] Save tab and scroll position which is shown before.

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#353]
## Overview (Required)
This is not mandatory feature.
If the user saw `ROOM1`, maybe s/he wants to see the same tab in the next time.

**Comment by nacatl** [comment]
Excuse me, I want to confirm the required spec.
I think you said as below. Isn't it?
- Even if the MainActivity is killed(f.g. Swiped out in recent apps), the Activity open with the same tab and the same scroll position when a user reinvokes the app.

**Comment by konifar** [comment]
@nacatl That's right!

**Comment by nacatl** [comment]
Thanks.
I think it is better for users that this feature can be ON(restore tab and position)/OFF(open default) by setting.

Can I try this?

**Comment by konifar** [comment]
Sure sure! Assigned. Thanks!

**Comment by nacatl** [comment]
@konifar 
I'm very sorry for my delay...
Report the current status.

I finished this issue, but the current code don't supported #493
So please wait a little, I will support that tab mode!
