### ISSUE TITLE
Add empty view in notification page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#355]
## Overview (Required)

<img width="451" alt="20180120_185221_screenshot_2018-01-20-18-51-50 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182197-46768d74-fe13-11e7-9b24-4ba11d41859b.png">

**Comment by nappannda** [comment]
🤚 

Is it possible to add an empty view of notifications to zeplin?

**Comment by konifar** [comment]
Sure, I'll ask the designer. Please wait his response for tomorrow (today)
Basically it would be same with My Sessions page's.
