### ISSUE TITLE
[Assigned] Floating day view is weird in My Sessions page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#357]
## Overview (Required)

<img width="449" alt="20180120_185750_screenshot_2018-01-20-18-56-41 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182222-d55814ae-fe13-11e7-90c4-d27dc1fb3ad4.png">

**Comment by nappannda** [comment]
🤚

**Comment by takahirom** [comment]
Thanks! Assigned 👍
