### ISSUE TITLE
[Assinged] Adjust sessions item margin

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#358]
## Overview (Required)

[Zeplin Design](https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a40dfc71687acd93721052e)

Actual | Design
:--: | :--:
<img width="453" alt="20180120_190017_screenshot_2018-01-20-18-59-07 jpg 1080x1920" src="https://user-images.githubusercontent.com/1269214/35182246-3f93593c-fe14-11e7-8c88-db093521f7a9.png"> | <img width="362" alt="20180120_190116_ _ - droidkaigi 2018 - zeplin" src="https://user-images.githubusercontent.com/1269214/35182252-4feba2f8-fe14-11e7-85ad-a5e9a0a4809b.png">

**Comment by nappannda** [comment]
🤚

**Comment by takahirom** [comment]
So Thanks 👍
