### ISSUE TITLE
Add debug menu 

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#359]
## Overview (Required)
We are using `Debot` to show debug menu.
https://github.com/DroidKaigi/conference-app-2018/blob/97de15f69bb23c56039df87094ebdd57b8b3a552/app/src/debug/java/io/github/droidkaigi/confsched2018/presentation/DebugApp.kt#L15

Debot supports custom debug menu by implementing `DebotStrategy`.
https://github.com/tomoima525/debot#custom-debugging-plugins

It would be great to create `Show notification` menu to make easy to check the notification apperance. What do you think?

**Comment by panpanini** [comment]
I'll try this! what type of notifications do we need to show? just the ones about upcoming sessions?

Also, should the debug menu offer input from the user, or just have default text?
