### ISSUE TITLE
When reselect BottomNavigationView scroll to current time session

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#361]
## Overview (Required)
- Title says everything

## Links
- https://github.com/DroidKaigi/conference-app-2018/issues/65#issuecomment-358045345

**Comment by konifar** [comment]
Is this same with https://github.com/DroidKaigi/conference-app-2018/issues/343 ?

**Comment by takahirom** [comment]
Yes! closed
