### ISSUE TITLE
Application CRASH on Android 4.4 emulator environment when starting

### ISSUE THREAD

**Issue by adakoda** [DroidKaigi/conference-app-2018#368]
## Overview (Required)
- **Application crash**

How to reproduce:
1. Make a following emulator environment by Android Virtual Device Manager.
  - **Nexus 5 API Level 19 (KitKat) x86 Android 4.4 (Google API)** <-- This env is **NG** 💣😇.
2. Launch Application(conference-app-2018).
3. Application will crash when starting.

If I use another emulator environment, it will work fine (no crash), such as
 - Nexus 6 API Level 21 (Lollipop) x86 Android 5.0.2 (Google API) <-- This env is **OK** 👍.
 - Nexus 5X API Level 23 (Marshmallow) x86 Android 6.0 (Google API) <-- This env is **OK** 👍.

![app_crash](https://user-images.githubusercontent.com/330223/35185290-955b1c52-fe45-11e7-85b7-9568edb99cb4.gif)

## Info
- Source code Revision: da0f013 : 2018/1/20 21:55
- Crashlytics report upload complete: **5A6366980177-0001-095C-439DEBF3290B** 👈👈👈
- LogCat:
  - [logcat.txt](https://github.com/DroidKaigi/conference-app-2018/files/1648954/logcat.txt)
  - <img width="959" alt="logcat" src="https://user-images.githubusercontent.com/330223/35185334-5dc448bc-fe46-11e7-96c5-124e284c98a3.png">

**Comment by takahirom** [comment]
Thank you for reporting!
Probably duplicate issue. But information is useful. thanks 👍 
https://github.com/DroidKaigi/conference-app-2018/issues/307
