### ISSUE TITLE
[Assigned] Change session difficulty icons to vector drawable

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#397]
## Overview (Required)
These icons in this PR.
https://github.com/DroidKaigi/conference-app-2018/pull/396

**Comment by gen0083** [comment]
Is there SVG files?
I tried convert png to SVG with <http://www.autotracer.org/> but cannot convert well...

**Comment by takahirom** [comment]
@gen0083 I invited Zeplin! And you can check icons
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a53b2cc33773142c504b949

**Comment by takahirom** [comment]
![image](https://user-images.githubusercontent.com/1386930/35192644-e52417f4-fed9-11e7-8905-65580cb6040b.png)
