### ISSUE TITLE
[Assigned] Session feedback screen

### ISSUE THREAD

**Issue by futabooo** [DroidKaigi/conference-app-2018#40]
## Overview (Required)
- With this feature, users can send feedback for session.
- use this link https://docs.google.com/forms/d/e/1FAIpQLSdNeo0djZbTRb1toK4mIRiVcgT4Gif6YZCk5b3WYEl-c77d5w/viewform
- https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java

**Comment by Pluu** [comment]
@futabooo  Since the link above is limited to Japanese, I also want an English version for overseas. Or how about adding English description?

**Comment by futabooo** [comment]
@Pluu I'm sorry I didn't make it clear enough.
I think this feature call the GooglForm API on sessionfeedback screen. 
How about implementing separating Japanese and English by display in conference application?

**Comment by Pluu** [comment]
@futabooo No Problem. 
Anything is OK. I think that "DroidKaigi Committee" also wants feedback other than Japan.

**Comment by konifar** [comment]
@Pluu @futabooo Thanks for great feedback!
Actually we'll add English texts on the same link as well as DroidKaigi 2017.
so it's okay to use the same url 😉

**Comment by konifar** [comment]
FYI: This is the same page in DroidKaigi2017
https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
