### ISSUE TITLE
[Assigned] We should use app intent rather than chrome custom tab.

### ISSUE THREAD

**Issue by ycrack** [DroidKaigi/conference-app-2018#402]
## Overview (Required)
- should use Intent instead of WebView

**Comment by takahirom** [comment]
It means if we go twitter, we should launch twitter?🤔

**Comment by ycrack** [comment]
🙆‍♂️

**Comment by takahirom** [comment]
That is good!

**Comment by kiuchikeisuke** [comment]
Is this issue not assigned yet? If so I will try this :raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned :+1:

**Comment by kiuchikeisuke** [comment]
I have a question. :worried:
When I call facebook App, it need to use specific scheme(fb://page/<FacebookId>).

So, Where should I write this specific sheceme ? (Because it is very limited usecase, I think that I write it as Fragment' Const)

**Comment by kiuchikeisuke** [comment]
sorry, I resolved it myself.. :sweat_smile:

**Comment by takahirom** [comment]
I'm sorry for late.🙇  I will think this

**Comment by takahirom** [comment]
You can modify this. I think It is ok to ignore Facebook.
https://github.com/droidkaigi/conference-app-2018/blob/47091b54a8eff835efdca781b6ada69f49666281/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/NavigationController.kt#L142-L142
You can see this implementation for reference
https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/externalnav/ExternalNavigationDelegateImpl.java?type=cs&q=resolveactivity+url+directory+src/chrome&sq=package:chromium&l=203
