### ISSUE TITLE
[Assigned] Apply feed(information) tab icons

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#413]
## Overview (Required)
- Only use icon in Zeplin
- You can use reference this.
https://github.com/DroidKaigi/conference-app-2018/pull/396
- There is no need to adjust the layout with this issue

## Links
- https://github.com/DroidKaigi/conference-app-2018/pull/396

If you raise hand, we will send Zeplin Invitation to you

- https://scene.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a527bbce212789e8ea30f1d
- icons: https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a53b2cc33773142c504b949
- screen: https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a523f970721c11708d20d66

**Comment by takahirom** [comment]
Notification types are `tutorial`, `notification`, `alert`, `enquete`

**Comment by sho5nn** [comment]
@takahirom  🙋‍♂️  `m.shogo330@gmail.com`
