### ISSUE TITLE
[Assigned] Apply feed layout design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#414]
## Overview (Required)
- Please adjust layout(Please note that Zeplin's font size is not designed.Please use `TextStyle.App.Xxxx` styles)

## Links
If you raise hand, we will send Zeplin Invitation to you
- https://scene.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a527bbce212789e8ea30f1d
- icons: https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a53b2cc33773142c504b949
- screen: https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a523f970721c11708d20d66

**Comment by sho5nn** [comment]
I'll do it.
