### ISSUE TITLE
We cannot tap favorite button when scroll-bar is shown beside it

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2018#425]
## Overview (Required)
- Fast scroll drawable intercepts touch event so we cannot tap favorite button

## Reproduce
- add 3 or 4 sessions as favorite
- move to my-session page
- when scroll-bar is shown we cannot tap favorite button

![ezgif-4-2e168e75ec](https://user-images.githubusercontent.com/7608725/35208126-fbff760c-ff89-11e7-822a-ca8b56408d84.gif)

**Comment by takahirom** [comment]
I don't have this solution 😭

**Comment by takahirom** [comment]
I think we should change 👍  48dp -> 32dp, 40dp -> 24dp
Because contents are more important
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/drawable/shape_fast_scroll_thumb.xml

**Comment by gen0083** [comment]
I try to modify 48dp -> 32dp and 40dp -> 24dp but still overlapped a little.
But favorite button of left side is able to tap :)

The problem is not completely solved, should I send PR in this state?

**Comment by takahirom** [comment]
If you have completely solved solution, Please do that. But I don't have that 😭

**Comment by gen0083** [comment]
Ok I'll try a little more 😄

**Comment by takahirom** [comment]
I appreciate it. 🙇 
I agree with using 16dp 👍
