### ISSUE TITLE
[Assigned] Fail unit tests when execute with whole test package

### ISSUE THREAD

**Issue by khronos227** [DroidKaigi/conference-app-2018#428]
## Overview (Required)
- As a title, if we execute unit tests with whole test package, it may fail on test of `DateSessionsSectionTest.kt` because of initialization error. (**left** of below)
- But if you run test only `DateSessionsSectionTest.kt`, it will success. (**right** of below)

| whole package test | one file test |
|:---:|:---:|
| <img width="762" alt="app_-_conference-app-2018_-____git_other_conference-app-2018_" src="https://user-images.githubusercontent.com/1215149/35210881-529a202c-ff97-11e7-94a7-fd78e1a2819a.png"> |<img width="773" alt="datesessionssectiontest_kt_-_conference-app-2018_-____git_other_conference-app-2018_" src="https://user-images.githubusercontent.com/1215149/35210886-5466d8e6-ff97-11e7-8981-5f5b7b1d9649.png"> |

※ so sorry if I run tests with wrong way.

**Comment by noriyuki106** [comment]
🙋

**Comment by konifar** [comment]
Thanks! I assigned 👍
