### ISSUE TITLE
[Assigned] Layout collapses when collapsing Toolbar in screen Session's detail

### ISSUE THREAD

**Issue by ushi3** [DroidKaigi/conference-app-2018#431]
## Overview (Required)
- In session detail screen, collapses up-icon and title content into toolbar when collapse toolbar

It seems that, layout margin inside CollapsingToolbarLayout is affecting

![collapsing_sample](https://user-images.githubusercontent.com/1962232/35215221-ebabab78-ffa6-11e7-8967-61006dddf459.gif)

**Comment by koji-1009** [comment]
🙋

**Comment by takahirom** [comment]
Thank!!!! Assigned 👍 😄
