### ISSUE TITLE
Session time incorrect when "Use local time" is enabled.

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2018#432]
## Overview (Required)
The reproduction procedure is as follows.

1. Visit Settings app.
1-1. Data & time > Set Time zone to London. (GMT+00:00)
1-2. Perform CLEAR DATA of droidkaigi2018 app.
2. Launch droidkaigi2018 app. (Sessions will be displayed soon.)
3. droidkaigi2018’s Settings > "Use local time" to enable.
4. Back to AllSessions screen.
   (Session sequence is incorrect.)

step2 ("Use local time" is Disable) | step4 ("Use local time" is Enable)
------------ | -------------
![pref_disable](https://user-images.githubusercontent.com/29206446/35215842-ec376544-ffa8-11e7-80c6-b80cf382384e.png) | ![pref_enable](https://user-images.githubusercontent.com/29206446/35215855-f9a21878-ffa8-11e7-8b4e-303702aa2f29.png)

This phenomenon seems to be related to the fact that toUnixMills () affects the following methods that generate objects.
* SessionWithSpeakers#toSession()
* SpecialSessions#getSessions()

Perhaps it may be necessary to reconsider the following tickets.
> Link Preference and behavior of settings that use local time #303

What is the thing application want to realize with ticket #303 ?

## Links
- #303
- #322

**Comment by takahirom** [comment]
I think the specification is following.

Use local time
not check -> always starts 10 o'clock
check -> starts 10 o'clock in Japan, but other time zones different time start

現地時間を使う
チェックしない→常に10時から始まる
チェックする→日本なら10時から、別のタイムゾーンではタイムゾーン毎の時間になる

**Comment by takahirom** [comment]
@nukka123 Thank you for reporting. We are helped by you. 🙇

**Comment by takahirom** [comment]
📝 
SpecialSession

```kotlin
                            Date(
                                    LocalDateTimeAdapter
                                            .parseDateString("2018-02-08T10:00:00")
                                            .toUnixMills()
                            ),
```

```kotlin
    companion object {
        private val FORMATTER: DateTimeFormatter =
                DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss")
        fun parseDateString(dateString: String?): LocalDateTime =
                LocalDateTime.parse(dateString, FORMATTER)
    }
```

```kotlin
fun LocalDateTime.toUnixMills(): Long {
    val timeZone = if (Prefs.enableLocalTime) {
        val defaultTimeZone = TimeZone.getDefault()
        toZoneId(defaultTimeZone.id)
    } else {
        toZoneId("JST")
    }
    return atZone(timeZone).toInstant().toEpochMilli()
}
```

**Comment by takahirom** [comment]
https://github.com/droidkaigi/conference-app-2018/blob/9c045ad14eef92ade7507a660f24156b12d7a110/app/src/main/java/io/github/droidkaigi/confsched2018/util/ext/DateExt.kt#L11-L11
