### ISSUE TITLE
No run windows environment.

### ISSUE THREAD

**Issue by Luecy1** [DroidKaigi/conference-app-2018#433]
## Overview (Required)
I clone this repository,and import project.
An error occurred when "Run 'app'".

But "Clean Project" and "Rebuild Project" is SUCCESSFUL.

Gradle Console
>
>Executing tasks: [:app:assembleDebug]
>
>Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
>The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
>registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
>registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
>app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.android.databinding:compiler:3.0.1'.
>:app:buildInfoDebugLoader
>:app:getDependencies
>:app:generateLicenses UP-TO-DATE
>:app:preBuild UP-TO-DATE
>:app:preDebugBuild UP-TO-DATE
>:app:compileDebugAidl UP-TO-DATE
>:app:compileDebugRenderscript UP-TO-DATE
>:app:checkDebugManifest UP-TO-DATE
>:app:generateDebugBuildConfig UP-TO-DATE
>:app:prepareLintJar UP-TO-DATE
>:app:mergeDebugShaders UP-TO-DATE
>:app:compileDebugShaders UP-TO-DATE
>:app:generateDebugAssets UP-TO-DATE
>:app:mergeDebugAssets UP-TO-DATE
>:app:processDebugGoogleServices
>Parsing json file: C:\Users\\Documents\conference-app-2018\app\google-services.json
>:app:createDebugCompatibleScreenManifests UP-TO-DATE
>:app:processDebugManifest UP-TO-DATE
>:app:fabricGenerateResourcesDebug UP-TO-DATE
>:app:generateDebugResValues UP-TO-DATE
>:app:generateDebugResources UP-TO-DATE
>:app:mergeDebugResources UP-TO-DATE
>:app:splitsDiscoveryTaskDebug UP-TO-DATE
>:app:processDebugResources UP-TO-DATE
>:app:generateDebugSources
>:model:compileKotlin UP-TO-DATE
>:model:compileJava NO-SOURCE
>:model:processResources NO-SOURCE
>:model:classes UP-TO-DATE
>:model:jar UP-TO-DATE
>:app:dataBindingExportBuildInfoDebug UP-TO-DATE
>:app:kaptGenerateStubsDebugKotlin UP-TO-DATE
>:app:transformDataBindingWithDataBindingMergeArtifactsForDebug UP-TO-DATE
>:app:kaptDebugKotlin UP-TO-DATE
>:app:compileDebugKotlin UP-TO-DATE
>:app:javaPreCompileDebug UP-TO-DATE
>:app:compileDebugJavaWithJavac
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\presentation\common\binding\FragmentBindingAdapters_Factory.java:8: エラー: シンボルを見つけられません
>public final class FragmentBindingAdapters_Factory implements Factory<FragmentBindingAdapters> {
>                                                                      ^
>  シンボル: クラス FragmentBindingAdapters
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\presentation\common\binding\FragmentBindingAdapters_Factory.java:16: エラー: シンボルを見つけられません
>  public FragmentBindingAdapters get() {
>         ^
>  シンボル:   クラス FragmentBindingAdapters
>  場所: クラス FragmentBindingAdapters_Factory
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\presentation\common\binding\FragmentBindingAdapters_Factory.java:20: エラー: シンボルを見つけられません
>  public static Factory<FragmentBindingAdapters> create(Provider<Fragment> fragmentProvider) {
>                        ^
>  シンボル:   クラス FragmentBindingAdapters
>  場所: クラス FragmentBindingAdapters_Factory
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\AboutThisAppActivityBuilder_ContributeAboutThisAppActivity.java:26: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, AboutThisAppActivityModule.class})
>                                                         ^
>  シンボル:   クラス AboutThisAppActivityModule
>  場所: クラス AboutThisAppActivityBuilder_ContributeAboutThisAppActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\ContributorActivityBuilder_ContributeContributorActivity.java:26: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, ContributorModule.class})
>                                                         ^
>  シンボル:   クラス ContributorModule
>  場所: クラス ContributorActivityBuilder_ContributeContributorActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\MainActivityBuilder_ContributeMainActivity.java:22: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, MainActivityModule.class})
>                                                         ^
>  シンボル:   クラス MainActivityModule
>  場所: クラス MainActivityBuilder_ContributeMainActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\MapActivityBuilder_ContributeMapActivity.java:22: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, MapActivityModule.class})
>                                                         ^
>  シンボル:   クラス MapActivityModule
>  場所: クラス MapActivityBuilder_ContributeMapActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\SessionDetailActivityBuilder_ContributeSessionDetailActivity.java:26: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, SessionDetailActivityModule.class})
>                                                         ^
>  シンボル:   クラス SessionDetailActivityModule
>  場所: クラス SessionDetailActivityBuilder_ContributeSessionDetailActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\SettingsActivityBuilder_ContributeSettingsActivity.java:25: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, SettingsActivityModule.class})
>                                                         ^
>  シンボル:   クラス SettingsActivityModule
>  場所: クラス SettingsActivityBuilder_ContributeSettingsActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\SpeakerDetailActivityBuilder_ContributeSpeakerDetailActivity.java:26: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, SpeakerDetailActivityModule.class})
>                                                         ^
>  シンボル:   クラス SpeakerDetailActivityModule
>  場所: クラス SpeakerDetailActivityBuilder_ContributeSpeakerDetailActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\SponsorsActivityBuilder_ContributeSponsorsActivity.java:25: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, SponsorsActivityModule.class})
>                                                         ^
>  シンボル:   クラス SponsorsActivityModule
>  場所: クラス SponsorsActivityBuilder_ContributeSponsorsActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\di\TopicDetailActivityBuilder_ContributeTopicDetailActivity.java:25: エラー: シンボルを見つけられません
>  @Subcomponent(modules = {FragmentBuildersModule.class, TopicDetailActivityModule.class})
>                                                         ^
>  シンボル:   クラス TopicDetailActivityModule
>  場所: クラス TopicDetailActivityBuilder_ContributeTopicDetailActivity
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\android\databinding\DataBinderMapper.java:56: エラー: シンボルを見つけられません
>                case io.github.droidkaigi.confsched2018.R.layout.fragment_settings:
>                                                                ^
>  シンボル:   変数 fragment_settings
>  場所: クラス layout
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\android\databinding\DataBinderMapper.java:260: エラー: シンボルを見つけられません
>                    return io.github.droidkaigi.confsched2018.R.layout.fragment_settings;
>                                                                      ^
>  シンボル:   変数 fragment_settings
>  場所: クラス layout
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\databinding\FragmentSettingsBinding.java:87: エラー: シンボルを見つけられません
>        return android.databinding.DataBindingUtil.<FragmentSettingsBinding>inflate(inflater, io.github.droidkaigi.confsched2018.R.layout.fragment_settings, root, attachToRoot, bindingComponent);
>                                                                                                                                         ^
>  シンボル:   変数 fragment_settings
>  場所: クラス layout
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\databinding\FragmentSettingsBinding.java:95: エラー: シンボルを見つけられません
>        return bind(inflater.inflate(io.github.droidkaigi.confsched2018.R.layout.fragment_settings, null, false), bindingComponent);
>                                                                                ^
>  シンボル:   変数 fragment_settings
>  場所: クラス layout
>C:\Users\MY_NAME\Documents\conference-app-2018\app\build\generated\source\kapt\debug\io\github\droidkaigi\confsched2018\presentation\common\binding\FragmentBindingAdapters_Factory.java:17: エラー: シンボルを見つけられません
>    return new FragmentBindingAdapters(fragmentProvider.get());
>               ^
>  シンボル:   クラス FragmentBindingAdapters
>  場所: クラス FragmentBindingAdapters_Factory
>注意:入力ファイルの操作のうち、未チェックまたは安全ではないものがあります。
>注意:詳細は、-Xlint:uncheckedオプションを指定して再コンパイルしてください。
>エラー17個
>
> FAILED
>:app:buildInfoGeneratorDebug
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':app:compileDebugJavaWithJavac'.
>> Compilation failed; see the compiler error output for details.
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>
>* Get more help at https://help.gradle.org
>
>BUILD FAILED in 37s
>
>30 actionable tasks: 5 executed, 25 up-to-date
>

**Comment by takahirom** [comment]
@Luecy1 Can it fix by using `rebuild`?

**Comment by Luecy1** [comment]
@takahirom
I'm sorry.
Reboot PC and "Run 'app'" is  BUILD SUCCESSFUL .

**Comment by takahirom** [comment]
Thanks!
