### ISSUE TITLE
[Assigned] Use tools:sample/** resources

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#441]
## Overview
- Probably we can use this 👍 
![image](https://user-images.githubusercontent.com/1386930/35225224-10357b94-ffcb-11e7-8650-2da8583d3445.png)

## Links
- https://developer.android.com/studio/write/tool-attributes.html#toolssample_resources

**Comment by takahirom** [comment]
There is no need to adapt to everything. try it.

**Comment by hiraok** [comment]
@takahirom Please let me do it！ ✋

**Comment by takahirom** [comment]
@hiraok Thank you! Another Doraemon!Assigned

**Comment by konifar** [comment]
Doraemon 🐱

**Comment by hiraok** [comment]
@konifar Your Doraemon is very wonderful!

**Comment by hiraok** [comment]
@takahirom Thank you for assigning!
