### ISSUE TITLE
[Assigned] Descent of the description area in the sessions page is cut off

### ISSUE THREAD

**Issue by noriyuki106** [DroidKaigi/conference-app-2018#447]
## Overview (Required)
- On my device, descent of the description area in the sessions page is cut off (as shown in the screenshot).
- My device is `arrows M03 (5.0inch, Android 6.0.1)`.
- #99 might be related to this issue

<img src="https://user-images.githubusercontent.com/3776241/35252995-6a5a3eec-0026-11e8-9c07-a2f69b55114b.png" width="320" />

**Comment by takahirom** [comment]
Thank you for reporting 👍

**Comment by nakker1218** [comment]
I'll try it 🙋

**Comment by konifar** [comment]
Thanks again! Assigned 👍
