### ISSUE TITLE
[Assigned] Show survey button and layout if session finished in Session Detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#451]
## Overview (Required)
- We should show survey button. 
- If you do this, We invite you to Zeplin 🎨 (Please note that Zeplin's font size is not designed.)
https://app.zeplin.io/project.html#pid=5a327a64f0b20176887c556c&sid=5a66b9288218dc236d2581d0&ref=slack
![image](https://user-images.githubusercontent.com/1386930/35258461-04aad814-0043-11e8-9bd2-9d4f87cebc39.png)

**Comment by takahirom** [comment]
🙋‍♂️

**Comment by konifar** [comment]
Thanks!
