### ISSUE TITLE
[Assigned] Launch google map app when tap address in MapActivity

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#454]
## Overview (Required)
- 🗾

## Links
-
![screenshot_20180123-213729](https://user-images.githubusercontent.com/1386930/35276128-a411669c-0085-11e8-8369-7821aad32be0.png)

**Comment by ronnnnn** [comment]
I'll try this !🙋‍♂️

**Comment by takahirom** [comment]
@ronnnnn Thanks!Assigned!
