### ISSUE TITLE
Characters are suffering in the "About this App" Screen

### ISSUE THREAD

**Issue by rkowase** [DroidKaigi/conference-app-2018#460]
## Overview (Required)
![untitled](https://user-images.githubusercontent.com/8059722/35282320-8a835952-0098-11e8-9ad7-cf4f38af2931.png)

**Comment by takahirom** [comment]
7.1 not reproduced

**Comment by takahirom** [comment]
Thank you for reporting🙇
What is your os?

**Comment by rkowase** [comment]
OS: Android 8.1.0

**Comment by rkowase** [comment]
Sorry, my font size setting was large.

Then I set the font size to default, it's not suffering
![untitled2](https://user-images.githubusercontent.com/8059722/35283076-8a179a9e-009a-11e8-95d5-cfe15ed60e61.png)
