### ISSUE TITLE
When submit search query, focus is still remain in search view

### ISSUE THREAD

**Issue by Kesin11** [DroidKaigi/conference-app-2018#462]
## Overview (Required)
When submit query with the search button of the keyboard in the search sessions, focus still remain in the search view.
As a result, keyboard is shown automatically when back from session details.
This behavior looks like a bug.

submit query
![submit_ime_button](https://user-images.githubusercontent.com/1324862/35286420-525dd8e4-00a3-11e8-9a23-d9a75acd3837.png)
⬇️ 
focus still remain in the search view
![remain_focus2](https://user-images.githubusercontent.com/1324862/35286667-f7626184-00a3-11e8-84a8-05f318e4d4b5.png)

May I fix it?

**Comment by takahirom** [comment]
@Kesin11 If you can, Please do it! 👍

**Comment by Kesin11** [comment]
Thank you. I'll do it 👍
