### ISSUE TITLE
[Assigned] Overlapping speaker and go to questionnaire button

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#467]
## Overview (Required)
- When there are two speakers, overlapping.
- You can check this by changing devie setting time

## Links
- ![screenshot_20180209-094131](https://user-images.githubusercontent.com/1386930/35308388-d901d4e4-00ea-11e8-95d7-def07dd3a81a.png)

**Comment by subroh0508** [comment]
I want to try it!

**Comment by konifar** [comment]
Thanks! Assigned! 👍
