### ISSUE TITLE
Cannot reveal BottomNavigationView when contents is short

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2018#471]
## Overview (Required)
- We cannot reveal BottomNavigationView some situation
- It happens when contents length is between BNV top and bottom
- Or contents length become shorter before BNV hiding

![cannot_reveal_bnv](https://user-images.githubusercontent.com/7608725/35334817-ed94b07c-0156-11e8-9834-b3b2799f0d24.gif)

Reproduce:

1. move to FeedFragment
1. expand all feeds to be able to scroll
1. scroll to downward and hide BNV
1. collapse all feeds to not be able to scroll
1. then we can not reveal BNV

**Comment by konifar** [comment]
Thanks for reporting!
