### ISSUE TITLE
[Assigned] Apply about this app medium button design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#482]
## Overview (Required)
Right map icon should become medium icon.
![image](https://user-images.githubusercontent.com/1386930/35421930-456ec5c0-0289-11e8-818f-74dbd03b9080.png)

If you do this, We invite you to Zeplin 🎨 (Please note that Zeplin's font size is not designed.)
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a53b2cc33773142c504b949
![image](https://user-images.githubusercontent.com/1386930/35421910-2e1bb310-0289-11e8-92de-ccc2bfb70c6b.png)

**Comment by ycrack** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
@ycrack Thanks! Assigned 👍
