### ISSUE TITLE
[Assigned] Adopt "Ignore-Prefix" to search speaker groups

### ISSUE THREAD

**Issue by amay077** [DroidKaigi/conference-app-2018#494]
## Overview (Required)

If first letter of author is "@", I hope ignore it in search speaker groups.

(Do you know well-known name for this feature?)

## Screenshot

<img src="https://user-images.githubusercontent.com/401369/35469357-8a176fd6-0376-11e8-99bd-fa24784485b9.png" width="300" />

**Comment by takahirom** [comment]
We should do it 👍 
And if we can, sort ignore case

**Comment by amay077** [comment]
Okay, I can do it. 👍

**Comment by takahirom** [comment]
@amay077 Thanks 👍 Assigned!

**Comment by amay077** [comment]
Thanks for merged :+1:
