### ISSUE TITLE
[assigned] FireBaseAnalytics.setCurrentScreen() on Fragment may not be called

### ISSUE THREAD

**Issue by ogapants** [DroidKaigi/conference-app-2018#500]
## Overview (Required)
(日本語で失礼します)

一部のFragmentで`FireBaseAnalytics.setCurrentScreen`が呼ばれないケースがあります。
そのFragmentとは、`AllSessionsFragment`や`SearchSessionsFragment`と、ViewPagerの中の最初のFragmentです。
一例として`SearchSessionsFragment`のライフサイクルは以下のようになります。

0. アプリを起動
0. bottom navigationで検索を選択
0. `SearchSessionsFragment`インスタンス生成
0. `setUserVisibleHint()`が呼ばれるが **ログは送れない**
0. `onAttach()`が呼ばれる
0. `onActivityCreated()`が呼ばれる（fireBaseAnalyticsインスタンスの初期化）
0. トピックタブ(`SearchTopicsFragment`)に移動、トピックタブのログは送れる
0. 再度セッションタブ(`SearchSessionsFragment`)に移動、この時の**ログは送れる**

現状`setUserVisibleHint()`でログを送っていますが、 上記の 3 の時点だと`fireBaseAnalytics` はまだnullなので実行されません。
たとえ`fireBaseAnalytics`の初期化タイミングを早めて実行できたとしても、まだこのときはAttachされておらず`getActivity()`がnullなので`setCurrentScreen()`を実行できません。

代わりに`ViewPager.OnPageChangeListener` を使って試そうとしましたが、あまりいいやり方にできなかったのでissueにしました 🤔 

## Links
- https://developer.android.com/reference/android/app/Fragment.html#setUserVisibleHint(boolean)

**Comment by takahirom** [comment]
これ難しいですね 🤔 
setUserVisibleHint()のときにgetActivityがnullなので送れないのが問題なんですよね？
誰かFragmentに強い人いますかね？

**Comment by jmatsu** [comment]
うちのアプリはsetUserVisibleHintの引数がtrue && view != nullで送ってますね。(ViewPagerの中に置くときのみ)
あとChildFragmentのsetUserVisibleHintが呼ばれないバグがあったので、親Fragmentから明示的に呼んでます。

**Comment by takahirom** [comment]
@jmatsu Viewから取得する方法なら初めて開いたときでもActivity context取得できるんですかね？

**Comment by takahirom** [comment]
すみません、実験してみます

**Comment by takahirom** [comment]
🤔 
![image](https://user-images.githubusercontent.com/1386930/35479004-10f96e24-042f-11e8-8c65-aecb6e15da0b.png)

**Comment by takahirom** [comment]
すごくかっこ悪いですが一応動きそう

```kotlin
    override fun setUserVisibleHint(isVisibleToUser: Boolean) {
        super.setUserVisibleHint(isVisibleToUser)
        if (isVisibleToUser) {
            if (fireBaseAnalytics != null) {
                fireBaseAnalytics?.setCurrentScreen(activity!!, null, this::class.java.simpleName)
            } else {
                Handler().post {
                    fireBaseAnalytics?.setCurrentScreen(activity!!, null, this::class.java.simpleName)
                }
            }
        }
    }
```

**Comment by kakajika** [comment]
少し冗長かもしれませんが、Rxの `withLatestFrom` を使ってイベントの待ち合わせをするという手もあります。

```kotlin
private val onActivityCreatedStream = PublishSubject.create<Activity>()
private val setUserVisibleHintStream = PublishSubject.create<Boolean>()

override fun onCreate(...) {
    super.onCreate(...)

    // onActivityCreated() が呼ばれた状態で、setUserVisibleHint() が呼ばれるたびに実行
    setUserVisibleHintStream
            .withLatestFrom(onActivityCreatedStream)
            .subscribe { (isVisibleToUser, activity) ->
                fireBaseAnalytics?.setCurrentScreen(activity, null, this::class.java.simpleName)
            }
            .addTo(...)
}

override fun onActivityCreated(...) {
    super.onActivityCreated(...)
    activity?.let { onActivityCreatedStream.onNext(it) }
}

override fun setUserVisibleHint(isVisibleToUser: Boolean) {
    super.setUserVisibleHint(isVisibleToUser)
    setUserVisibleHintStream.onNext(isVisibleToUser)
}
```

ご参考までに 😃

**Comment by satoshun** [comment]
`FragmentStatePagerAdapter`クラスを拡張して頑張ることも出来そうだなと思いました。

```java
public abstract class FragmentStatePagerAdapter2 extends FragmentStatePagerAdapter {
    private FragmentPagerActiveListener currentListener = null;

    public FragmentStatePagerAdapter3(FragmentManager fm) {
        super(fm);
    }

    @Override
    public void setPrimaryItem(ViewGroup container, int position, Object object) {
        super.setPrimaryItem(container, position, object);
        if (object instanceof FragmentPagerActiveListener) {
            if (object != currentListener) {
                ((FragmentPagerActiveListener) object).visibleFragment((Activity) container.getContext());
            }
            currentListener = (FragmentPagerActiveListener) object;
            return;
        }
        currentListener = null;
    }

    interface FragmentPagerActiveListener {
        void visibleFragment(Activity activity);
    }
}
```

**Comment by takahirom** [comment]
もしやっていただける方いれば募集します 🙇 
開いた時にsetCurrentScreenが呼ばれればOKです

**Comment by satoshun** [comment]
やりたいです 💪💪💪

**Comment by takahirom** [comment]
@satoshun Thanks!!! 💪

**Comment by eneim** [comment]
Assigned されたが、コメントだけさせてください :D, ```setUserVisibleHint(true)``` でしかログを送信するようであれば、```FragmentStatePagerAdapter```を実装する時に、```FragmentStatePagerAdapter#setPrimaryItem()``` をOverrideして、何とかできるかもしれません :D (setUserVisibleHint()に「**true**」が渡されたのはこのメソッドでしか呼ばれないわけですね)

**Comment by ogapants** [comment]
I learned a lot, thanks! 😃
