### ISSUE TITLE
[Assigned] Prevent returning even if I erase the keyboard at search time

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#503]
## Overview (Required)
- Title says everything

![matanmj32ftakahirom01282018150334](https://user-images.githubusercontent.com/1386930/35479505-8d24ac2c-043c-11e8-963e-8d8b79520a20.gif)

**Comment by from-unknown** [comment]
Oh no...
I made this bug 🙇 
Please let me fix it.

**Comment by takahirom** [comment]
@from-unknown Thanks! Assigned 👍 🙇

**Comment by mhidaka** [comment]
Don't mind!
