### ISSUE TITLE
[Assigned] Coexist with the debug version and the release version of the app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#505]
## Overview (Required)
- When I install the debug app and release app, It shows the error message.

> Failed to install /Users/takahirom/git/conferenceapp2018/app/build/outputs/apk/debug/app-debug.apk: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/io.github.droidkaigi.confsched2018.debug-1: Can't install because provider name io.github.droidkaigi.confsched2018.presentation.search.SearchSuggestionProvider (in package io.github.droidkaigi.confsched2018.debug) is already used by io.github.droidkaigi.confsched2018]

- I think We should change this value when debug 
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/AndroidManifest.xml#L186

**Comment by takahirom** [comment]
Probably we can change it by using manifestPlaceholders.
https://github.com/DroidKaigi/conference-app-2018/blob/b4e55b86119a8bb3df2a09884afc60f76a868446/app/build.gradle#L67
Or overriding debug Manifest.xml
https://github.com/DroidKaigi/conference-app-2018/blob/b4e55b86119a8bb3df2a09884afc60f76a868446/app/src/debug/AndroidManifest.xml

**Comment by kawmra** [comment]
@takahirom 
How about changing the SearchSuggestionProvider's authorities attribute like `${applicationId}.presentation.search.SearchSuggestionProvider` ?

https://developer.android.com/studio/build/manifest-build-variables.html

I think it resolves package conflict.

**Comment by takahirom** [comment]
@kawmra That's good 👍 
Probably we should create extended SearchSuggestionProvider in debug package? 🤔 
Can you do this? 😄

**Comment by kawmra** [comment]
@takahirom 
I think the `android:name` attribute specifies actual class.
so I don't think we need create another class.

I think just changing `android:authorities` attribute would be fine.
(sorry for not having perfect understanding 😅 )

what do you think?

**Comment by takahirom** [comment]
@kawmra Thanks! I misunderstood!👍

**Comment by kawmra** [comment]
@takahirom 
thanks 🙏 

but maybe AUTHORITY constant of [this](https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchSuggestionProvider.kt#L7-L8) must be changed.
May I contribute for this?

**Comment by takahirom** [comment]
@kawmra Sure! Thanks!
