### ISSUE TITLE
[Assigned] Apply textIsSelectable = true for session details

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#514]
## Overview (Required)
- I want to google it 😄

**Comment by masaibar** [comment]
🙋

**Comment by takahirom** [comment]
@masaibar Thanks! Assigned 👍

**Comment by masaibar** [comment]
@takahirom I made selectable only detail text. Should I make selectable all texts in this screen?

<image src="https://user-images.githubusercontent.com/8677433/35483505-2eebfa9e-0486-11e8-952b-484602858efe.png" width=300>

**Comment by takahirom** [comment]
You can do as you like. 👍 
I think it is enough

**Comment by masaibar** [comment]
Thank you !
I made selectable the session title too.
