### ISSUE TITLE
[Assigned] Add Google search item when select text in session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#517]
## Overview (Required)
-
 <image src="https://user-images.githubusercontent.com/8677433/35483505-2eebfa9e-0486-11e8-952b-484602858efe.png" width=300/ >

**Comment by kazkn** [comment]
I wish try this! 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned:+1:
