### ISSUE TITLE
[Assigned] High light current session card of the background

### ISSUE THREAD

**Issue by kiuchikeisuke** [DroidKaigi/conference-app-2018#521]
## Overview (Required)
- ![screenshot_20180129-112143](https://user-images.githubusercontent.com/2305231/35490963-b70cffbc-04e6-11e8-8e05-78a9c00b40c3.png)

- I think that it is better to change the color of the background of session card so that we can more easily notice the currently open session

## Links
-

**Comment by takahirom** [comment]
We should do it 😄

**Comment by takahirom** [comment]
Thanks! Assigned 👍
