### ISSUE TITLE
[Assigned] Speaker name is not displayed on SearchSessionsFragment screen.

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2018#528]
## Overview (Required)
This is bug repot. 

before (#439) | now (name is not displayed)
------------ | -------------
![search_ok](https://user-images.githubusercontent.com/29206446/35509165-788e1f14-0536-11e8-8e7e-6767f4a3d30f.png) | ![search_fail](https://user-images.githubusercontent.com/29206446/35509191-906122b2-0536-11e8-8e03-f0c03509199e.png)

## Links
-

**Comment by takahirom** [comment]
Thanks 👍 That's bug

**Comment by nukka123** [comment]
The cause was found out.

item_horizontal_session.xml
```
<io.github.droidkaigi.confsched2018.presentation.common.view.SpeakersSummaryLayout
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toStartOf="@id/favorite"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@id/title"
    app:speakers="@{session.speakers}"
    />
```
->  app:textColor is not specified.

SpeakersSummaryLayout.kt
```
val defaultAttributes = CustomAttributes(
        textColor = 0
)

```
-> This means full transparent color.

**Comment by nukka123** [comment]
ok. i fix it.

**Comment by takahirom** [comment]
Thanks!!!😂😂
