### ISSUE TITLE
[Assigned] Fix ellipsis in Speakers

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#55]
## Overview (Required)
- If the text is long, we should change text end like this "..."

## Screenshot
<img src="https://user-images.githubusercontent.com/1386930/34730799-c4945cc2-f5a3-11e7-8a83-73b15adc51dc.png" width="300" />

**Comment by AAkira** [comment]
🙋

**Comment by konifar** [comment]
@AAkira 🆒

**Comment by takahirom** [comment]
@AAkira 🥇

**Comment by AAkira** [comment]
@takahirom @konifar 

I'm going to write in style.
How is it?

Like this

```
 <style name="Text.SingleLine">
        <item name="android:ellipsize">end</item>
        <item name="android:maxLines">1</item>
</style>

<style name="Text.DoubleLine">
        <item name="android:ellipsize">end</item>
        <item name="android:maxLines">2</item>
        <item name="android:lineSpacingMultiplier">@dimen/hoge</item> <!-- optional -->
    </style>
```
Text size and color is set by text appearance.
Do you have a policy of style?

**Comment by takahirom** [comment]
@AAkira I think It is good 👍 
This text appearances based [Material Design Dense script](https://material.io/guidelines/style/typography.html)
I think that it is better to use Style and TextAppearance in combination. How about this?

```xml
<TextView
  style="@style/Text.SingleLine"
  android:textAppearance="@style/TextAppearance.App.Caption"

**Comment by konifar** [comment]
@AAkira Thanks for good suggestion!
There is no policy for now.
but in my opinion, it's better not to create style to specify maxLines.
I prefer using style to specify textSize and textColor like below.

```
TextTitle
TextTitle.Primary
TextTitle.Grey
TextSubhead
...
```

If we add the styles to specify maxLines, the number of the styles would be getting increased. So for this fix, I think it's better not to create styles.

**Comment by AAkira** [comment]
@konifar 
Ok, I follow your opinion 👍 

But, I think textSize and textColor should be set by TextAppearance.
I look forward to discuss about this in Droid Kaigi. 😄

**Comment by konifar** [comment]
@AAkira Good! I created issue just now.
https://github.com/DroidKaigi/conference-app-2018/issues/77

I'll try to create the draft guideline for it. I would be happy if you join the discussion. Thanks!
