### ISSUE TITLE
[Assigned] It makes it possible to go to the whole survey of the navigation drawer.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#551]
## Overview (Required)
-  https://github.com/DroidKaigi/conference-app-2018/blob/63f038aec2b3547c1acc0a1957516e5bd5eda731/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/menu/DrawerMenu.kt#L118
![image](https://user-images.githubusercontent.com/1386930/35662390-37c36044-075b-11e8-800e-fb827a912309.png)

## Links
- this is the link!
- https://goo.gl/forms/Hjp54vk5P0VILcgf1

**Comment by panpanini** [comment]
I'll do this! 🙋

**Comment by takahirom** [comment]
@panpanini Thanks 👍
