### ISSUE TITLE
[Assigned] Change recents title text color to white

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#56]
## Overview (Required)
- Probably you should use `TaskDescription`

## Screenshot
<img src="https://user-images.githubusercontent.com/1386930/34732884-ee4b034e-f5a9-11e7-9865-e5b2f6de1afe.png" width="300" />

**Comment by konifar** [comment]
FYI
https://github.com/DroidKaigi/conference-app-2017/blob/1231fd2d3cef97a2181f72627f30692bf1815d45/app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java#L74

**Comment by keima** [comment]
@takahirom 

Unfortunately, We cannot change recents text color to white unless change background color (#FBC812).

I'll provide 2 workaround:

1. Use TaskDescription color to contrast ratio 3:1 (e.g. #B88E0F )

<img src="https://user-images.githubusercontent.com/867470/34919209-d7ea8c12-f9a2-11e7-98c7-11900124ec3c.png" width="400" />

pros: Generality
cons: Murky color compared to primary color, Mismatch tab layout color

( check color contrast ratio here : https://webaim.org/resources/contrastchecker/ )

2. Set empty title text

<img src="https://user-images.githubusercontent.com/867470/34919214-e05e0ba8-f9a2-11e7-99b7-a90f5f825ec4.png" width="400" />

pros: Match color
cons: Not generality ( I never seen even once ), Not apply close button color to white

Of course, another choice that keeping text color to black (keep current) is available.

**Comment by konifar** [comment]
Voted the first one 🙋‍♂️

**Comment by takahirom** [comment]
I voted the first one. 👍

**Comment by takahirom** [comment]
I will ask @yuki2478

**Comment by punchdrunker** [comment]
:one:

**Comment by keima** [comment]
Thanks for voting!
I'll try this by plan 1 tonight (JST), but I'm ready to try another decision designer @yuki2478 thinking.
