### ISSUE TITLE
The text of FeedFragment is clipped.

### ISSUE THREAD

**Issue by adakoda** [DroidKaigi/conference-app-2018#565]
## Overview (Required)
This is a bug report.

## Links
![1](https://user-images.githubusercontent.com/330223/35763541-efbe1832-08f1-11e8-9b20-ab6fcb9a5b52.png)
![2](https://user-images.githubusercontent.com/330223/35763542-f16b3a3e-08f1-11e8-8bb7-e9e47e434643.png)

**Comment by takahirom** [comment]
The layout is here 🤔 
https://github.com/droidkaigi/conference-app-2018/blob/50a2ba426104fc9d004fb3fa91279f41f47f4555/app/src/main/res/layout/item_feed.xml#L52-L52
