### ISSUE TITLE
[Assigned] The lunch session has needless "/"

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#58]
## Overview (Required)
- The lunch session has needless "/"
- Probably you should modify item_special_session.xml

## Screenshot
<img src="https://user-images.githubusercontent.com/1386930/34808073-abcab556-f6cf-11e7-9f51-7d820730ef8b.png" width="300" />

**Comment by kumamotone** [comment]
🙋‍♂️

**Comment by konifar** [comment]
@kumamotone Thanks! Assigned! 👍  Feel free to ask us when you have any questions.

**Comment by kumamotone** [comment]
Thank you! I created https://github.com/DroidKaigi/conference-app-2018/pull/89. 
If something wrong, please feel free to tell 🙇
