### ISSUE TITLE
[Assigned] Faster Circle CI build by caching Bundle install

### ISSUE THREAD

**Issue by tyutyu08** [DroidKaigi/conference-app-2018#580]
## Overview (Required)
- Ruby dependencies can be cached as well as Android SDK and library dependent caching.
- If you do so, you can shorten the build time, though slightly.

## Links
- https://circleci.com/docs/2.0/language-ruby/

May I create a pull request?

**Comment by takahirom** [comment]
Thanks! It is must!! 👍  Please do it 🙇
