### ISSUE TITLE
Tap while scrolling for some reason, bottom navigation will be displayed

### ISSUE THREAD

**Issue by noxi515** [DroidKaigi/conference-app-2018#582]
## Overview (Required)
- Tap while scrolling for some reason, bottom navigation will be displayed.

**Comment by takahirom** [comment]
In japanese (セッション一覧画面でスクロールするとBotttomNavigation消えるけど、スクロール中に（スクロールが停止する前に）再度タッチでスクロールするとBottomNavigationが再表示される)
