### ISSUE TITLE
Can't Start

### ISSUE THREAD

**Issue by OldBigBuddha** [DroidKaigi/conference-app-2018#583]
## Overview (Required)
DeplayGateの＃351で起動ができません
エラー内容は以下でした
02-04 11:32:01.670 29993 29993 E AndroidRuntime: FATAL EXCEPTION: main
02-04 11:32:01.670 29993 29993 E AndroidRuntime: Process: io.github.droidkaigi.confsched2018, PID: 29993
02-04 11:32:01.670 29993 29993 E AndroidRuntime: b.k: lateinit property binding has not been initialized
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.a.o_(AllSessionsFragment.kt:109)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.common.view.a.c(OnTabReselectedListener.kt:21)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.support.design.widget.TabLayout.g(TabLayout.java:1177)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.support.design.widget.TabLayout.b(TabLayout.java:1136)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.support.design.widget.TabLayout.b(TabLayout.java:1128)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.support.design.widget.TabLayout$e.e(TabLayout.java:1427)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.l$c.onChanged(SessionsFragment.kt:99)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.support.v4.view.p.c(PagerAdapter.java:292)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.q.a(SessionsFragment.kt:225)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.q.b(SessionsFragment.kt:270)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.q.a(SessionsFragment.kt:255)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.l$d.a(SessionsFragment.kt:114)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.presentation.sessions.l$d.a(SessionsFragment.kt:38)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at io.github.droidkaigi.confsched2018.util.a.g$a.a(LiveDataExt.kt:9)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData.a(LiveData.java:109)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData.b(LiveData.java:126)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData.b(LiveData.java:282)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.o.b(MutableLiveData.java:33)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.t$2$1.a(Transformations.java:145)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.m$a.a(MediatorLiveData.java:152)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData.a(LiveData.java:109)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData.b(LiveData.java:126)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData.b(LiveData.java:282)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5480)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-04 11:32:01.670 29993 29993 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

## Links
-

**Comment by takahirom** [comment]
Thanks 👍 And Sorry 
We are working on fixing that 🙇

**Comment by OldBigBuddha** [comment]
環境はZenfone2でAndroid6.0.1です
