### ISSUE TITLE
When switching time based sessions, I want to see current time session

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#589]
## Overview (Required)
- Title says everything.
- You can check it by changing device time
![image](https://user-images.githubusercontent.com/1386930/35775154-d1afbe7e-09c6-11e8-96f8-6d02e05aee08.png)

**Comment by seisuke** [comment]
Current time session has been opened already at the master branch.
But it works at time and room based session screen.
![device-2018-02-06-162644](https://user-images.githubusercontent.com/53058/35846941-f52aa756-0b5b-11e8-8c23-1507b33844b5.png)

**Comment by takahirom** [comment]
@seisuke Thanks, I think that is good. 👍 
I think it is better to show DAY1 / 14:00 tab.
What do you think? 🤔

**Comment by seisuke** [comment]
I implement to show current session tab.
