### ISSUE TITLE
Memory leak by tab logic

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#590]
## Overview (Required)
- This leak is not only sessions 😭 
- https://github.com/DroidKaigi/conference-app-2018/pull/577#issuecomment-362874431

![image](https://user-images.githubusercontent.com/1386930/35775529-6256bd00-09cd-11e8-8f8d-52e844cc7651.png)

**Comment by ogapants** [comment]
https://twitter.com/new_runnable/status/960062516251340800
I'll check it!

**Comment by ogapants** [comment]
@takahirom Sorry,
Could you tell me the procedure for reproducing?

**Comment by takahirom** [comment]
@ogapants I don't have reproducing method. 😭  But I think Kotlin object is the singleton. So it is leaking.
Can you stop cache fragment? like this https://github.com/DroidKaigi/conference-app-2018/pull/493/files#diff-8fa8830b5e88e5e809ec4e5ea4be2e6cR195
It occurred another leaking
![image](https://user-images.githubusercontent.com/1386930/35775747-289e0b0e-09d2-11e8-9946-6c5210890fce.png)

**Comment by ogapants** [comment]
@takahirom 
ご迷惑おかけしてすみません！
ちょっと2点確認させてください。

1.
ちょっと最新のmasterのdebug版でBottomNaviの検索周りをいじってみてもそのleakcanaryが再現しないのですが、↓こちらでのFragmentの取得もそのような取得方法を取ればいいですかね？
https://github.com/ogapants/conference-app-2018/blob/3da6872e19921cdc20a3947bdacee3cc3f1a2cbc/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/SearchFragment.kt#L238-L238
手元で事前に再現させて見たいので、もし操作する上で決まり手のようなものがあれば教えていただきたいです。

2. 
また、[このPR](https://github.com/DroidKaigi/conference-app-2018/pull/577)でFragmentの取得方法を変更したのは理由があります。
今までの方法だと、[`OnTabReselectedListener`で`getItem()`が呼ばれると](https://github.com/ogapants/conference-app-2018/blob/01545b96062ea9be61ece7827caec72ad54e9037/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/OnTabReselectedListener.kt#L19-L19)新たに`newInstance`されたFragmentが返り、`scrollToTop()`内の`binding`が初期化されてない状態なので`kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized`が起きます。
今は取得方法が元に戻ったので、現在のタブを再選択するとこの問題でクラッシュしてしまいます 😭 
↓を参考に、`instantiateItem`を使って現在のFragmentを取得する方法を取ってみます！
https://qiita.com/chooblarin/items/88b4accac0cbb6944d4b

**Comment by takahirom** [comment]
@ogapants それいま修正されてmasterに入っています！！話ややこしくしてすみません！ 🙇

**Comment by ogapants** [comment]
@takahirom なるほど！すみません！1だけやります！！！

**Comment by takahirom** [comment]
検索タブ開いて終了を繰り返して極稀にという感じですね。。
![image](https://user-images.githubusercontent.com/1386930/35776252-3fc853ac-09dc-11e8-8398-e4eee6ac7603.png)

**Comment by ogapants** [comment]
手元でもなにかをきっかけに稀に再現することを確認しました、、、↑の対応取ってみたところ発生しなくなった気がするので、とりあえずPR投げてみますね 🙏
