### ISSUE TITLE
Bottom Navigation will be never shown

### ISSUE THREAD

**Issue by nacatl** [DroidKaigi/conference-app-2018#599]
## Overview (Required)
- At first, scroll to below for hiding the bottom navigation.
- Secondly, disable 'BottomNavigationを隠す'.
- Then back to SessionsFragment, users can't display the bottom navigation

![never_shown_bottom_navigation](https://user-images.githubusercontent.com/26807657/35778090-9235fc3c-09fc-11e8-9450-2e2c81fb6dc4.gif)

**Comment by takahirom** [comment]
Thanks!
