### ISSUE TITLE
[Assigned] Create custom view for speakers

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#61]
## Overview (Required)
- Currently, we should write binding logic for speakers image and text for each session.

## Screenshot
<img src="https://user-images.githubusercontent.com/1386930/34856878-0c3ce542-f78b-11e7-82b9-569162127c04.png" width="200" />

**Comment by YusukeIwaki** [comment]
I want to contribute to this issue 🙆‍♂️
