### ISSUE TITLE
Too small notification icon

### ISSUE THREAD

**Issue by ctake0005** [DroidKaigi/conference-app-2018#619]
## Overview (Required)
- The notification icon size of each dpi is too small. (For example, xxxhdpi contains 48 x 48 px, but should be 96 x 96 px.)
- I will attach a screenshot taken with pixel. 
![status-bar](https://user-images.githubusercontent.com/9300164/35842808-eb84cd76-0b47-11e8-94d8-e81b561d9f69.png)

## Links
- https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html#size11

**Comment by takahirom** [comment]
The icon is here
The icon is 36dp 😭 
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/drawable-xxhdpi/ic_notification.png

**Comment by ctake0005** [comment]
Oh, the original icon size is small...
OK, I'll try to crop it out from the launcher icon.
