### ISSUE TITLE
[Assigned] Use Shinjuku Grand Tower 1F, 5F instead of Shinjuku Grand Tower 5F

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#620]
## Overview (Required)
- We should use `1F, 5F`  for access

## Links
-　
![image](https://user-images.githubusercontent.com/1386930/35845113-2f04e124-0b54-11e8-8d79-6205a37bef51.png)

**Comment by hironytic** [comment]
🙋

**Comment by konifar** [comment]
Thanks! Assigned

**Comment by takahirom** [comment]
Thanks!!!!!! 🙇 🙇
