### ISSUE TITLE
[Help wanted] Speaker icon quickly tapped issue

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2018#628]
## Overview (Required)
- when I tapped speaker icon quickly, SpeakerDetailActivity launch twice
- press back button twice then speaker icon is not shown
- the icon will be shown by re-bind with scroll or move to other Fragment

![ezgif-4-92c871ff15](https://user-images.githubusercontent.com/7608725/35859695-69ae3098-0b84-11e8-82b4-911a59c11851.gif)

**Comment by takahirom** [comment]
This issue is difficult. When I try using shared element transition, I could not fix it 🤔

**Comment by jmatsu** [comment]
I guess SpeakerDetailActivity can be single instance so that should we change launch mode?
 I'm not sure it will work fine for this problem though....
