### ISSUE TITLE
[Assigned] Use emoji compat library

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#63]
## Overview (Required)
- Some session using emoji. So I think it is better to use emoji compatibility library for device and os compatibility.

## Links
- https://droidkaigi.jp/2018/timetable?session=16836

**Comment by Pluu** [comment]
Report the test results.

## Configurate

- com.android.support:support-emoji:27.0.2

```
val fontRequest = FontRequest(
                "com.google.android.gms.fonts",
                "com.google.android.gms",
                "Noto Color Emoji Compat",
                R.array.com_google_android_gms_fonts_certs)
```

## Test Device

- Android 4.4.2 (Kitkat)

##  Preview

- Title : android.support.text.emoji.widget.EmojiTextView
- Description : android.support.text.emoji.widget.EmojiTextView

Session List | Session Detail
-- | --
<img src="https://user-images.githubusercontent.com/1534926/35001000-297c461a-fb29-11e7-9cca-8a4e7b4fabbd.png" width="300px" />  |  <img src="https://user-images.githubusercontent.com/1534926/35001064-5342e490-fb29-11e7-9125-fdc96cc5eda4.png" width="300px" />

**Comment by Pluu** [comment]
:raising_hand:

**Comment by konifar** [comment]
@Pluu Thanks! Assigned

**Comment by takahirom** [comment]
@PluuI wanted to implement, but I have not done it yet, so I will hand it over to you. 👍
