### ISSUE TITLE
[Assigned] Shared element transition between "speakers in search screen" and "speaker detail screen"

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#64]
## Overview (Required)
- I think we can use shared element transition with speaker image
![image](https://user-images.githubusercontent.com/1386930/34858712-330509e8-f795-11e7-9480-a9d86e259946.png)

**Comment by miga9** [comment]
🙋‍♂️ !

**Comment by konifar** [comment]
@miga9 Thanks! I assigned you 👍

**Comment by konifar** [comment]
@miga9 Hi, can you try this? 
Sorry for rush but if you don't have time to do, it's okay to remove the assign.
What do you think?

**Comment by miga9** [comment]
Hi @konifar, thanks for checking. I was struggling a bit with the target activity having fragment. I hope to have a PR up this weekend.

**Comment by konifar** [comment]
@miga9 Thank you so much! I appreciate it!

**Comment by miga9** [comment]
@konifar, Is it a must that we keep Fragment inside Activity for all screens?

**Comment by takahirom** [comment]
@miga9
I think the yellow layout of SpeakerDetailFragment can be bring to Activity. Are there any other layouts you would like to bring to Activity?

**Comment by miga9** [comment]
@takahirom, Thanks for your response! I was able to get it to work without getting rid of the fragment. I'm cleaning it up and will have a PR soon.

**Comment by takahirom** [comment]
@miga9 It is amazing!
