### ISSUE TITLE
[Assigned] Scroll by current time

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#65]
# Overview
We want to see the current session. So we should scroll sessions for current session when opening the app.

**Comment by sho5nn** [comment]
I think that this is a good function to growth up UX. :)

**Comment by sho5nn** [comment]
@takahirom @konifar OK, I know #199, I hit on a good idea. Scroll to current session when reselected BottomNavigationView, How about ?

**Comment by konifar** [comment]
@sho5nn Genius 💡
