### ISSUE TITLE
[Assigned] Error build cache 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#666]
## Overview (Required)
- CircleCI Build cache is not working
- We should fix here https://github.com/DroidKaigi/conference-app-2018/blob/master/.circleci/config.yml#L13
- https://circleci.com/gh/DroidKaigi/conference-app-2018/1378

```
Error computing cache key: template: cacheKey:1:8: executing "cacheKey" at <checksum "build.grad...>: error calling checksum: open /home/circleci/project/build.gradle: no such file or directory
```

**Comment by shikajiro** [comment]
ノ

**Comment by takahirom** [comment]
Thanks 👍 Assigned
