### ISSUE TITLE
[Assigned] Swap language Japanese and English in SearchSessionsFragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#69]
## Overview (Required)
- If Language preference setting is English, We should replace Japanese and English.

❌
```
初心者向け
For beginner
```

⭕

```
For beginner
初心者向け
```

- You can see similar implementation
 [TopicItem](https://github.com/droidkaigi/conference-app-2018/blob/e28d635e7e7ef9667971d85200a4b1dd35522617/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/search/item/TopicItem.kt#L25-L25)

## Screenshot
<img src="https://user-images.githubusercontent.com/1386930/34875451-a2e87560-f7e0-11e7-9624-dd51f1556b6a.png" width="300" />

**Comment by nyanyoni** [comment]
🙋

**Comment by konifar** [comment]
@nyanyoni Great 👍
