### ISSUE TITLE
[Assigned] Sticky label for SearchSpeakersFragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#70]
## Overview (Required)
- We want to implement sticky label behavior. 

## Links
- It probably need ItemDecoration like this https://github.com/cephus/AdvancedRecyclerView/blob/master/app/src/main/java/com/codeundone/advancedrecyclerview/decoration/complex/ComplexDecoration.java#L98

## Screenshot
Zeplin screenshot.
<img src="https://user-images.githubusercontent.com/1386930/34901901-5e32ec10-f854-11e7-9dff-26d2d9ec3ee2.png" width="300" />
We can see that behavior on Android Contact app

**Comment by e10dokup** [comment]
🙋

**Comment by konifar** [comment]
Thanks! Assigned 👍

**Comment by e10dokup** [comment]
@takahirom @konifar Can I get Zeplin's invitation?

**Comment by konifar** [comment]
@e10dokup Sure! Sent invitation to your email address which is registered in GitHub!

**Comment by e10dokup** [comment]
@konifar Thanks! I confirmed Zeplin's screens!
