### ISSUE TITLE
[Assigned] Fix typo

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#73]
## Overview (Required)
⚡️ 

https://github.com/droidkaigi/conference-app-2018/blob/38a1caf1ed1a996d63fbea75adf0bd8725eeb36a/app/src/main/java/io/github/droidkaigi/confsched2018/data/db/FavoriteFireStoreDatabase.kt#L167-L167

**Comment by yagi2** [comment]
🙋

**Comment by konifar** [comment]
@yagi2 Thanks for quick tackle!
