### ISSUE TITLE
[Assigned]Replace hardcoded text to  strings.xml

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#75]
## Overview (Required)
`DAY1`
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/layout/fragment_room_sessions.xml#L22

@takahirom If this is intentional, please close this issue 🙇

**Comment by takahirom** [comment]
Great 👍 
This is not my intentional

**Comment by kawmra** [comment]
🙋

**Comment by takahirom** [comment]
@kawmra Thanks! Assigned 👍

**Comment by kawmra** [comment]
@takahirom @konifar

https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/layout/fragment_all_sessions.xml#L25
In this layout, corresponding TextView has `tools:text` attribution with hardcoded string `DAY 1`.

May I fix this issue same way?

**Comment by konifar** [comment]
@kawmra yea, I'd like to. but is there any way to use replacement strings like `DAY%d` for `tools:text`?

**Comment by kawmra** [comment]
@konifar 
I think `DAY 1` is just for placeholder in layout editor.
Actual value like 'DAY%d' seems to be generated in https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sessions/RoomSessionsFragment.kt#L108 .
so I think this issue will be resolved to change attribution `android:text` to `tools:text`.

how do you think about that?

**Comment by konifar** [comment]
Ah sorry. I misunderstood your comment!
Yes, you are right!

> so I think this issue will be resolved to change attribution android:text to tools:text.

**Comment by kawmra** [comment]
sorry for my ambiguous comment 🙏
