### ISSUE TITLE
[Assigned] Map screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2018#8]
# Overview
With this feature, Users can know where droidkaigi will be held.
This screen uses google map API.
You should implement [MapFragment](https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/map/MapFragment.kt)
 
Design
https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a532ae6a02185f395b28c3e

**Comment by atsuya046** [comment]
I want to try 🙋‍♂️

**Comment by konifar** [comment]
🆒  Thanks! Assigned and send the invitation to see Zeplin!
