### ISSUE TITLE
[Assigned] Toolbar text should be center vertical

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#90]
## Overview (Required)
Toolbar text seems to be a little above the center :eyes:

<img width="446" alt="20180113_162629_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34903913-9d14da22-f87e-11e7-842d-29744157fad1.png">

**Comment by beta1139** [comment]
I want to contribute to this issue :ok_woman:
