### ISSUE TITLE
[Assigned] topic_total_session should be plurals text

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#94]
## Overview (Required)
This text should be plural. so it's better to use `<plurals>` tag.

```xml
<string name="topic_total_session">%dsessions</string>
```

https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/values/strings.xml#L59

**Comment by KoutaMatsushita** [comment]
🙋

**Comment by konifar** [comment]
@KoutaMatsushita Thanks! I assigned you!
