### ISSUE TITLE
[Assigned]Add pretty animation for the favorite button

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#96]
## Overview (Required)
I want pretty animation of the favorite button on the sessions page and session detail page 😄 
Like twitter or something.
It's good chance to try to use AnimatedVectorDrawable.

## Links
-

## Screenshot
<img src="" width="300" />

**Comment by neonankiti** [comment]
@yuki2478 give us some animation, okapi〜. or is it?

**Comment by YusukeIwaki** [comment]
I want to try this issue if no one already assigned

**Comment by takahirom** [comment]
@YusukeIwaki Thanks! 👍 Assigned
I am looking forward to animation ❤️
