### ISSUE TITLE
[Assigned]Add padding on the bottom text in the session detail

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#98]
## Overview (Required)
I think it's better to add `4dp` padding here.

<img src="https://user-images.githubusercontent.com/1269214/34904263-bccf51ce-f885-11e7-8bd1-188bdcd03d87.png" width="300">

**Comment by e10dokup** [comment]
🙋

**Comment by konifar** [comment]
Thanks!! Assinged you!
