### ISSUE TITLE
[Assigned]The description area in the sessions page is cut off.

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2018#99]
## Overview (Required)
<img width="507" alt="20180113_171913_asus z00ad" src="https://user-images.githubusercontent.com/1269214/34904274-fc2d5956-f885-11e7-8035-db744e3857e3.png">

**Comment by shanonim** [comment]
Can I try this? 🙋

**Comment by konifar** [comment]
@shaninim Sure! Thanks!
@takahirom Can you share Zeplin to him?

**Comment by takahirom** [comment]
🙆

**Comment by takahirom** [comment]
@shanonim Could you tell me an email address on twitter direct message?

**Comment by shanonim** [comment]
@takahirom I sent message. Thanks!

**Comment by shanonim** [comment]
I checked this issue but It seems ok 🤔  (Device: Nexus5X, Android8.0)
Should I check other pages?
Please tell me the detail, Thanks! @konifar 

<img src="https://user-images.githubusercontent.com/5153307/34906250-03b4c4d0-f8ad-11e7-9f96-b8fb0c383f5b.png" width=400>

**Comment by konifar** [comment]
Hmm, it happens on my device 🤔 
Android 5.1
Zenfone2

**Comment by konifar** [comment]
It might be linespacing issue in the `TextAppearance`.

```
android:textAppearance="@style/TextAppearance.App.Caption"
```

**Comment by takahirom** [comment]
Is it this? https://material.io/guidelines/style/typography.html#typography-line-height
Probably it is defined, but I don't know it's dp size. 🤔

**Comment by takahirom** [comment]
Sorry probably my misunderstanding

**Comment by konifar** [comment]
It's specified text size as `sp` but it contains own line-spacing. I'm not sure it's the result for this though.

**Comment by shanonim** [comment]
I reproduced it on 5.5inch screen size device (Android 5.1.1) 👍 

<img src="https://user-images.githubusercontent.com/5153307/34906404-6307b6a6-f8b0-11e7-8ef8-5a2e4e8f211f.png" width=400>
